export const compoundsData = new Map([
  ["H2", { type: "otherNonMetals" }],
  ["O2", { type: "lanthanoid" }],
  ["H2O", { type: "alkalineEarth" }],
  ["Cl2", { type: "actinoid" }],
  ["HCl", { type: "inert" }],
  ["NaOH", { type: "transition" }],
  ["NaCl", { type: "alkali" }],
  ["Na", { type: "otherNonMetals" }],
  ["Li", { type: "inert" }],
  ["LiH", { type: "alkali" }],
  ["NaH", { type: "inert" }],
  ["K", { type: "otherMetals" }],
  ["KH", { type: "halogens" }],
  ["Rb", { type: "lanthanoid" }],
  ["RbH", { type: "alkali" }],
  ["Cs", { type: "inert" }],
  ["CsH", { type: "alkali" }],
  ["Fr", { type: "alkalineEarth" }],
  ["FrH", { type: "transition" }],
  ["F2", { type: "otherMetals" }],
  ["HF", { type: "actinoid" }],
  ["I2", { type: "transition" }],
  ["HI", { type: "alkali" }],
  ["Br2", { type: "transition" }],
  ["HBr", { type: "alkalineEarth" }],
  ["Ca", { type: "lanthanoid" }],
  ["CaH2", { type: "halogens" }],
  ["Sr", { type: "otherNonMetals" }],
  ["SrH2", { type: "halogens" }],
  ["Ba", { type: "actinoid" }],
  ["BaH2", { type: "halogens" }],
  ["Ra", { type: "transition" }],
  ["RaH2", { type: "alkalineEarth" }],
  ["B", { type: "otherMetals" }],
  ["B2H6", { type: "alkali" }],
  ["BH3", { type: "actinoid" }],
  ["Al", { type: "lanthanoid" }],
  ["AlH3", { type: "actinoid" }],
  ["Sn", { type: "alkalineEarth" }],
  ["SnH4", { type: "halogens" }],
  ["N2", { type: "inert" }],
  ["NH3", { type: "actinoid" }],
  ["P", { type: "actinoid" }],
  ["PH3", { type: "inert" }],
  ["S", { type: "otherMetals" }],
  ["H2S", { type: "otherMetals" }],
  ["Se", { type: "halogens" }],
  ["H2Se", { type: "halogens" }],
  ["Te", { type: "halogens" }],
  ["H2Te", { type: "alkali" }],
  ["As", { type: "inert" }],
  ["AsH3", { type: "actinoid" }],
  ["Sb", { type: "actinoid" }],
  ["SbH3", { type: "inert" }],
  ["HClO", { type: "actinoid" }],
  ["C", { type: "transition" }],
  ["CO2", { type: "inert" }],
  ["CO", { type: "otherMetals" }],
  ["Na2O", { type: "alkalineEarth" }],
  ["Fe", { type: "otherMetals" }],
  ["FeO", { type: "otherNonMetals" }],
  ["Fe2O3", { type: "halogens" }],
  ["Fe(OH)3", { type: "alkalineEarth" }],
  ["CaO", { type: "otherMetals" }],
  ["Ca(OH)2", { type: "alkali" }],
  ["CaCO3", { type: "alkalineEarth" }],
  ["CaCl2", { type: "otherNonMetals" }],
  ["Al2O3", { type: "actinoid" }],
  ["AlCl3", { type: "otherNonMetals" }],
  ["NaAlO2", { type: "lanthanoid" }],
  ["Na2CO3", { type: "otherMetals" }],
  ["Al(OH)3", { type: "otherNonMetals" }],
  ["HNO3", { type: "halogens" }],
  ["Ca(NO3)2", { type: "alkalineEarth" }],
  ["H2CO3", { type: "transition" }],
  ["NaNO3", { type: "transition" }],
  ["NaNO2", { type: "otherMetals" }],
  ["CaC2", { type: "transition" }],
  ["AgNO3", { type: "transition" }],
  ["AgCl", { type: "lanthanoid" }],
  ["NaClO", { type: "actinoid" }],
  ["NO", { type: "lanthanoid" }],
  ["NO2", { type: "actinoid" }],
  ["HNO2", { type: "alkalineEarth" }],
  ["Zn(OH)2", { type: "otherNonMetals" }],
  ["Zn(NO3)2", { type: "alkali" }],
  ["NH4OH", { type: "otherMetals" }],
  ["NH4NO3", { type: "lanthanoid" }],
  ["H2SO4", { type: "halogens" }],
  ["(NH4)2SO4", { type: "otherMetals" }],
  ["P2O5", { type: "transition" }],
  ["H3PO4", { type: "otherMetals" }],
  ["Na3PO4", { type: "actinoid" }],
  ["Ca(PO4)2", { type: "otherMetals" }],
  ["PCl3", { type: "alkalineEarth" }],
  ["PCl5", { type: "halogens" }],
  ["Ca3(PO4)2", { type: "otherMetals" }],
  ["CaHPO4", { type: "transition" }],
  ["SO2", { type: "lanthanoid" }],
  ["H2SO3", { type: "otherMetals" }],
  ["BaCl2", { type: "actinoid" }],
  ["BaSO4", { type: "inert" }],
  ["KOH", { type: "halogens" }],
  ["KCl", { type: "actinoid" }],
  ["KNO3", { type: "lanthanoid" }],
  ["H2O2", { type: "otherMetals" }],
  ["Pb(NO3)2", { type: "otherMetals" }],
  ["PbSO4", { type: "otherMetals" }],
  ["Na2S", { type: "alkalineEarth" }],
  ["Zn", { type: "otherMetals" }],
  ["ZnS", { type: "otherMetals" }],
  ["ZnCl2", { type: "halogens" }],
  ["PbS", { type: "halogens" }],
  ["Pb", { type: "transition" }],
  ["Pb(OH)2", { type: "halogens" }],
  ["PbO", { type: "otherMetals" }],
  ["PbCl2", { type: "alkalineEarth" }],
  ["K3[Al(OH)6]", { type: "otherMetals" }],
  ["Mg(OH)2", { type: "otherNonMetals" }],
  ["MgCl2", { type: "transition" }],
  ["MgO", { type: "transition" }],
  ["Cu(OH)2", { type: "alkali" }],
  ["CuCl2", { type: "alkalineEarth" }],
  ["HOCl", { type: "actinoid" }],
  ["FeCl3", { type: "inert" }],
  ["Cu", { type: "inert" }],
  ["FeS", { type: "alkali" }],
  ["FeCl2", { type: "otherNonMetals" }],
  ["CuSO4", { type: "halogens" }],
  ["Na2SO4", { type: "inert" }],
  ["CuO", { type: "otherMetals" }],
  ["Cu2O", { type: "inert" }],
  ["FeSO4", { type: "alkali" }],
  ["ZnSO4", { type: "inert" }],
  ["SO3", { type: "actinoid" }],
  ["Fe(OH)2", { type: "actinoid" }],
  ["NaHSO4", { type: "inert" }],
  ["Cu(NO3)2", { type: "actinoid" }],
  ["Ba(NO3)2", { type: "halogens" }],
  ["NaSO4", { type: "otherMetals" }],
  ["Cu(NO)3", { type: "otherNonMetals" }],
  ["Ca(HCO3)2", { type: "alkalineEarth" }],
  ["Ca(HNO3)2", { type: "otherMetals" }],
  ["Mg", { type: "actinoid" }],
  ["NaHCO3", { type: "inert" }],
  ["CaCl", { type: "alkalineEarth" }],
  ["ZnO", { type: "otherMetals" }],
  ["K2[Zn(OH)4]", { type: "actinoid" }],
  ["K2SO4", { type: "actinoid" }],
  ["CaSO4", { type: "otherNonMetals" }],
  ["NaH2PO4", { type: "halogens" }],
  ["Na2HPO4", { type: "halogens" }],
  ["Na2SO3", { type: "lanthanoid" }],
  ["NaSO3", { type: "otherMetals" }],
  ["CaS", { type: "halogens" }],
  ["K2CO3", { type: "transition" }],
  ["Ca(OH2)", { type: "inert" }],
  ["NH4Cl", { type: "lanthanoid" }],
  ["NH4HCO3", { type: "halogens" }],
  ["KNO2", { type: "otherNonMetals" }],
  ["NH2Cl", { type: "transition" }],
  ["KClO3", { type: "actinoid" }],
  ["Ca(H2PO4)2", { type: "lanthanoid" }],
  ["SiO2", { type: "alkalineEarth" }],
  ["Na2SiO3", { type: "transition" }],
  ["K2SiO3", { type: "alkali" }],
  ["CaSiO3", { type: "otherNonMetals" }],
  ["Fe3O4", { type: "actinoid" }],
  ["Fe3C", { type: "inert" }],
  ["MgCO3", { type: "otherNonMetals" }],
  ["MgSiO3", { type: "transition" }],
  ["CuS", { type: "alkali" }],
  ["CuFeS2", { type: "halogens" }],
  ["ZnCO3", { type: "otherMetals" }],
  ["BaS", { type: "otherNonMetals" }],
  ["Pb3O4", { type: "lanthanoid" }],
  ["MnO2", { type: "otherMetals" }],
  ["Mn", { type: "actinoid" }],
  ["Al(NO3)3", { type: "otherNonMetals" }],
  ["Al2(SO4)3", { type: "lanthanoid" }],
  ["AlO2H", { type: "otherMetals" }],
  ["Na[Al(OH)4]", { type: "halogens" }],
  ["MoO3", { type: "otherNonMetals" }],
  ["Mo", { type: "otherMetals" }],
  ["WO3", { type: "otherNonMetals" }],
  ["W", { type: "alkali" }],
  ["TiCl4", { type: "otherMetals" }],
  ["TiO2", { type: "otherNonMetals" }],
  ["HClO4", { type: "otherNonMetals" }],
  ["H2Cl2O8", { type: "halogens" }],
  ["HgCl2", { type: "otherMetals" }],
  ["Hg", { type: "otherNonMetals" }],
  ["NaI", { type: "actinoid" }],
  ["NaBr", { type: "otherNonMetals" }],
  ["Ag", { type: "otherNonMetals" }],
  ["LiCl", { type: "otherNonMetals" }],
  ["HgO", { type: "lanthanoid" }],
  ["Cl2O", { type: "actinoid" }],
  ["ClO2", { type: "lanthanoid" }],
  ["HClO2", { type: "alkali" }],
  ["HClO3", { type: "otherNonMetals" }],
  ["ClO3", { type: "otherNonMetals" }],
  ["Cl2O7", { type: "inert" }],
  ["HPO3", { type: "lanthanoid" }],
  ["Na3AlO3", { type: "alkali" }],
  ["Li2O", { type: "actinoid" }],
  ["Li2O2", { type: "halogens" }],
  ["Na2O2", { type: "transition" }],
  ["K2O2", { type: "halogens" }],
  ["Li3N", { type: "lanthanoid" }],
  ["LiO2", { type: "alkali" }],
  ["NaO2", { type: "alkalineEarth" }],
  ["K2O", { type: "lanthanoid" }],
  ["KO2", { type: "halogens" }],
  ["RbO2", { type: "inert" }],
  ["CsO2", { type: "lanthanoid" }],
  ["FrO2", { type: "alkali" }],
  ["Rb2O", { type: "transition" }],
  ["Cs2O", { type: "transition" }],
  ["Fr2O", { type: "lanthanoid" }],
  ["Rb2O2", { type: "actinoid" }],
  ["Cs2O2", { type: "transition" }],
  ["Fr2O2", { type: "alkali" }],
  ["Be", { type: "actinoid" }],
  ["BeO", { type: "transition" }],
  ["SrO", { type: "otherMetals" }],
  ["BaO", { type: "halogens" }],
  ["RaO", { type: "transition" }],
  ["CaO2", { type: "otherNonMetals" }],
  ["BeO2", { type: "actinoid" }],
  ["MgO2", { type: "lanthanoid" }],
  ["SrO2", { type: "transition" }],
  ["BaO2", { type: "halogens" }],
  ["RaO2", { type: "transition" }],
  ["Be(OH)2", { type: "inert" }],
  ["Sr(OH)2", { type: "alkali" }],
  ["Ba(OH)2", { type: "halogens" }],
  ["Ra(OH)2", { type: "inert" }],
  ["B2O3", { type: "actinoid" }],
  ["Ga", { type: "actinoid" }],
  ["Ga2O3", { type: "alkali" }],
  ["In", { type: "transition" }],
  ["In2O3", { type: "otherMetals" }],
  ["Tl", { type: "otherMetals" }],
  ["Tl2O3", { type: "alkalineEarth" }],
  ["Tl2O", { type: "otherMetals" }],
  ["B(OH)3", { type: "alkalineEarth" }],
  ["TlO", { type: "halogens" }],
  ["MgH2", { type: "otherNonMetals" }],
  ["BeH2", { type: "actinoid" }],
  ["Si", { type: "otherNonMetals" }],
  ["Ge", { type: "inert" }],
  ["GeO2", { type: "transition" }],
  ["GeO", { type: "inert" }],
  ["SnO2", { type: "otherMetals" }],
  ["PbO2", { type: "otherMetals" }],
  ["H2SnI6", { type: "alkalineEarth" }],
  ["Sn(SO4)2", { type: "otherMetals" }],
  ["2Pb(NO3)2", { type: "otherNonMetals" }],
  ["PbCO3", { type: "actinoid" }],
  ["Na2[Pb(OH)6]", { type: "otherMetals" }],
  ["Cr(OH)3", { type: "alkali" }],
  ["K2CrO4", { type: "halogens" }],
  ["K2PbO2", { type: "transition" }],
  ["N2O", { type: "otherNonMetals" }],
  ["NaNH2", { type: "alkalineEarth" }],
  ["NaN3", { type: "alkali" }],
  [" NaNO3", { type: "otherMetals" }],
  [" N2O", { type: "otherMetals" }],
  ["NH3OHCl", { type: "transition" }],
  ["H2N2O2", { type: "transition" }],
  ["NOCl", { type: "otherMetals" }],
  ["N2O3", { type: "inert" }],
  ["Cr2O3", { type: "alkalineEarth" }],
  ["N2O5", { type: "inert" }],
  ["H2SnO3", { type: "inert" }],
  ["N2O4", { type: "alkalineEarth" }],
  ["P4O10", { type: "actinoid" }],
  ["P4O6", { type: "inert" }],
  ["O3", { type: "transition" }],
  ["SeO2", { type: "inert" }],
  ["K[Pb(OH)3]", { type: "otherNonMetals" }],
  ["Pb2CO3(OH)2", { type: "otherMetals" }],
  ["Na2SeO3", { type: "inert" }],
  ["H2SeO3", { type: "alkali" }],
  ["TeO2", { type: "lanthanoid" }],
  ["SeO3", { type: "transition" }],
  ["K2SeO4", { type: "inert" }],
  ["Se2O5", { type: "alkalineEarth" }],
  ["SeF4", { type: "actinoid" }],
  ["SeO2F2", { type: "actinoid" }],
  ["NaF", { type: "transition" }],
  ["OF2", { type: "halogens" }],
  ["Na2PbO2", { type: "alkali" }],
  ["MnSO4", { type: "actinoid" }],
  ["HMnO4", { type: "alkalineEarth" }],
  ["Sb2O3", { type: "alkalineEarth" }],
  ["Sb2S3", { type: "alkali" }],
  ["As2O3", { type: "alkalineEarth" }],
  ["As2S3", { type: "halogens" }],
  ["AsCl3", { type: "otherMetals" }],
  ["AsF3", { type: "halogens" }],
  ["Ag2O3", { type: "otherNonMetals" }],
  ["H3AsO4", { type: "otherMetals" }],
  ["As2O5", { type: "halogens" }],
  ["Bi", { type: "otherNonMetals" }],
  ["Bi2O3", { type: "actinoid" }],
  ["Bi(NO3)3", { type: "actinoid" }],
  ["BiCl3", { type: "alkalineEarth" }],
  ["BiF3", { type: "halogens" }],
  ["B2S3", { type: "transition" }],
  ["BiOCl", { type: "inert" }],
  ["NaBiO3", { type: "alkali" }],
  ["Na3BiO4", { type: "inert" }],
  ["Bi2O5", { type: "actinoid" }],
  ["CeO2", { type: "otherNonMetals" }],
  ["Ce2O3", { type: "alkalineEarth" }],
  ["Ce(SO4)2", { type: "inert" }],
  ["CeCl3", { type: "actinoid" }],
  ["Ce", { type: "actinoid" }],
  ["CrO3", { type: "otherMetals" }],
  ["H2CrO4", { type: "lanthanoid" }],
  ["H2Cr2O7", { type: "inert" }],
  ["Na2Cr2O7", { type: "actinoid" }],
  ["H3PO2", { type: "otherMetals" }],
  ["CrO", { type: "lanthanoid" }],
  ["CrHg3", { type: "alkalineEarth" }],
  ["Cr", { type: "alkali" }],
  ["CrHg", { type: "inert" }],
  ["(NH4)2Cr2O7", { type: "alkali" }],
  ["CrO2", { type: "actinoid" }],
  ["CrCl3", { type: "alkali" }],
  ["K2Cr2O7", { type: "lanthanoid" }],
  ["KCrO2", { type: "actinoid" }],
  ["NaCrO2", { type: "alkalineEarth" }],
  ["Na2CrO4", { type: "inert" }],
  ["Cr(NO3)3", { type: "lanthanoid" }],
  ["CrO2Cl2", { type: "transition" }],
  ["CrO(OH)", { type: "halogens" }],
  ["Co3O4", { type: "halogens" }],
  ["CoO", { type: "halogens" }],
  ["CoCl2", { type: "alkalineEarth" }],
  ["Co(OH)2", { type: "halogens" }],
  ["Co", { type: "alkali" }],
  ["CoSO4", { type: "halogens" }],
  ["Co2(CO)8", { type: "lanthanoid" }],
  ["Na2[Co(OH)4]", { type: "alkalineEarth" }],
  ["Co2SiO4", { type: "alkali" }],
  ["(CoAl2)O4", { type: "otherNonMetals" }],
  ["NaCoO2", { type: "halogens" }],
  ["Co(OH)3", { type: "alkalineEarth" }],
  ["Co2O3", { type: "alkalineEarth" }],
  ["Co(NO3)2", { type: "alkalineEarth" }],
  ["H[CuCl2]", { type: "otherMetals" }],
  ["NaHSO3", { type: "inert" }],
  ["Cu2S", { type: "lanthanoid" }],
  ["Cu2Cl2O", { type: "otherMetals" }],
  ["Cu3N", { type: "transition" }],
  ["BaCu2O2", { type: "alkalineEarth" }],
  ["CuN3", { type: "halogens" }],
  ["CuI", { type: "halogens" }],
  ["KI", { type: "alkali" }],
  ["CuOH", { type: "alkali" }],
  ["Cu2CO3(OH)2", { type: "inert" }],
  ["CuCO3", { type: "alkali" }],
  ["K2CuO2", { type: "alkali" }],
  ["Na[Cu(OH)4]", { type: "inert" }],
  ["FeC2O4", { type: "transition" }],
  ["FeCO3", { type: "lanthanoid" }],
  ["Fe(NO3)3", { type: "transition" }],
  ["Na4FeO3", { type: "actinoid" }],
  ["Zn(FeO2)2", { type: "lanthanoid" }],
  ["FeO(OH)", { type: "halogens" }],
  ["Fe2(SO4)3", { type: "inert" }],
  ["NaFeO2", { type: "inert" }],
  [" NaOH", { type: "otherMetals" }],
  ["Na5FeO4", { type: "otherNonMetals" }],
  ["LaCl3", { type: "alkali" }],
  ["La(OH)3", { type: "actinoid" }],
  ["La2O3", { type: "alkali" }],
  ["La2S3", { type: "halogens" }],
  ["CS2", { type: "transition" }],
  ["La2(SO4)3", { type: "inert" }],
  ["La(BO2)3", { type: "inert" }],
  ["La", { type: "lanthanoid" }],
  ["La(NO3)3", { type: "halogens" }],
  ["La2(CO3)3", { type: "actinoid" }],
  ["La2(C2O4)3", { type: "halogens" }],
  ["LaCO3(OH)", { type: "otherNonMetals" }],
  ["Pb2(OH)2CO3", { type: "otherMetals" }],
  [" PbO2", { type: "otherNonMetals" }],
  ["K2[Pb(OH)4]", { type: "lanthanoid" }],
  ["K2[Pb(OH)6]", { type: "lanthanoid" }],
  ["LiOH", { type: "lanthanoid" }],
  ["Li2CO3", { type: "otherMetals" }],
  ["MnO", { type: "actinoid" }],
  ["MnCO3", { type: "halogens" }],
  ["Mn2O7", { type: "otherNonMetals" }],
  ["KMnO4", { type: "otherMetals" }],
  ["MnCl2", { type: "inert" }],
  ["K2MnO4", { type: "otherNonMetals" }],
  ["Mn(SO4)2", { type: "otherMetals" }],
  ["CaMnO3", { type: "alkali" }],
  ["Mn2O3", { type: "halogens" }],
  ["KHSO4", { type: "alkalineEarth" }],
  ["Mn3O4", { type: "alkalineEarth" }],
  ["Zn[Mn2O4]", { type: "halogens" }],
  ["La[MnO3]", { type: "lanthanoid" }],
  ["HgS", { type: "halogens" }],
  ["NiO", { type: "inert" }],
  ["NiCrO4", { type: "lanthanoid" }],
  ["Ni", { type: "alkalineEarth" }],
  ["Ni(OH)2", { type: "inert" }],
  ["NiCO3", { type: "alkali" }],
  ["NiCl2", { type: "otherMetals" }],
  ["Na2NiO2", { type: "alkali" }],
  ["BaNiO2", { type: "otherNonMetals" }],
  ["Ni2SiO4", { type: "halogens" }],
  ["Ni2O3", { type: "halogens" }],
  ["Ni3O4", { type: "actinoid" }],
  ["RbOH", { type: "alkalineEarth" }],
  ["RbNO3", { type: "lanthanoid" }],
  ["SiCl4", { type: "alkalineEarth" }],
  ["Na2Si3O7", { type: "otherMetals" }],
  ["SiH4", { type: "lanthanoid" }],
  ["H2SiF6", { type: "inert" }],
  [" Na4SiO4", { type: "otherMetals" }],
  ["SiO", { type: "inert" }],
  ["H2[SiF6]", { type: "alkali" }],
  ["Na4SiO4", { type: "otherMetals" }],
  ["Na2CaSi6O14", { type: "inert" }],
  ["Ag2O", { type: "inert" }],
  ["AgF", { type: "otherNonMetals" }],
  ["AgBr", { type: "transition" }],
  ["AgI", { type: "otherMetals" }],
  ["AgOH", { type: "transition" }],
  ["KCN", { type: "otherMetals" }],
  ["K[Ag(CN)2]", { type: "alkali" }],
  ["[Ag(NH3)2]OH", { type: "otherNonMetals" }],
  ["Ag2NH", { type: "halogens" }],
  ["TlOH", { type: "actinoid" }],
  ["Tl2CO3", { type: "alkalineEarth" }],
  ["TlNO3", { type: "transition" }],
  ["TlCl3", { type: "inert" }],
  ["Tl(NO3)3", { type: "actinoid" }],
  ["TlH(SO4)2", { type: "otherMetals" }],
  ["NaTlO2", { type: "inert" }],
  ["H[TlCl2]", { type: "alkali" }],
  ["Tl2S3", { type: "halogens" }],
  ["Th", { type: "otherMetals" }],
  ["ThO2", { type: "alkalineEarth" }],
  ["Th(OH)4", { type: "alkalineEarth" }],
  ["Th(NO3)4", { type: "transition" }],
  ["Th(CO3)2", { type: "transition" }],
  ["Th(C2O4)2", { type: "alkalineEarth" }],
  ["ThF4", { type: "alkali" }],
  ["ThS2", { type: "alkalineEarth" }],
  ["ThSiO4", { type: "transition" }],
  ["ThCl4", { type: "alkali" }],
  ["Th(SO4)2", { type: "transition" }],
  ["SnO", { type: "alkali" }],
  ["Sn3O4", { type: "halogens" }],
  ["Sn(OH)2", { type: "inert" }],
  ["SnC2O4", { type: "transition" }],
  ["SnCl2", { type: "alkalineEarth" }],
  ["SnSO4", { type: "alkali" }],
  ["H[SnCl3]", { type: "lanthanoid" }],
  ["Na[Sn(OH)3]", { type: "transition" }],
  ["Na2SnO2", { type: "otherNonMetals" }],
  ["SnS", { type: "otherMetals" }],
  ["H2(SnCl6)", { type: "lanthanoid" }],
  ["Na2[Sn(OH)6]", { type: "otherMetals" }],
  ["Na2SnO3", { type: "halogens" }],
  ["SNO2", { type: "transition" }],
  ["K4SnO4", { type: "alkali" }],
  ["U3O8", { type: "transition" }],
  ["UO3", { type: "actinoid" }],
  ["UO2(OH)2", { type: "otherMetals" }],
  ["(NH4)2U2O7", { type: "inert" }],
  ["(UO2)Cl2", { type: "inert" }],
  ["(UO2)SO4", { type: "lanthanoid" }],
  ["Na2U2O7", { type: "transition" }],
  ["Na2UO4", { type: "lanthanoid" }],
  ["UF6", { type: "alkalineEarth" }],
  ["BrO2", { type: "halogens" }],
  ["NaBrO3", { type: "otherNonMetals" }],
  ["Br2O", { type: "inert" }],
  ["HgBr2", { type: "otherNonMetals" }],
  ["I2O5", { type: "otherMetals" }],
  ["NaBrO", { type: "alkali" }],
  ["Na2C2O4", { type: "halogens" }],
  ["COCl2", { type: "lanthanoid" }],
  ["(FCO)2O2", { type: "alkalineEarth" }],
  ["KF", { type: "lanthanoid" }],
  ["COS", { type: "transition" }],
  ["HCOOK", { type: "halogens" }],
  ["K2C2O2", { type: "otherNonMetals" }],
  ["HCN", { type: "alkali" }],
  ["Fe(CO)5", { type: "otherMetals" }],
  ["CsOH", { type: "alkali" }],
  ["FrOH", { type: "lanthanoid" }],
  ["Ti", { type: "otherNonMetals" }],
  ["TiAl", { type: "transition" }],
  ["Eu", { type: "alkalineEarth" }],
  ["EuAs", { type: "actinoid" }],
  ["LiGa", { type: "transition" }],
  ["MgTi", { type: "transition" }],
  ["NiTi", { type: "alkalineEarth" }],
  ["TiNi", { type: "transition" }],
  ["U", { type: "lanthanoid" }],
  ["U3Si2", { type: "inert" }],
  ["V", { type: "alkalineEarth" }],
  ["Be12V", { type: "alkalineEarth" }],
  ["CeAl3", { type: "alkali" }],
  ["Cr2Al", { type: "alkali" }],
  ["Al3Ti", { type: "inert" }],
  ["Ti3Al", { type: "otherNonMetals" }],
  ["Er", { type: "actinoid" }],
  ["ErCo2", { type: "halogens" }],
  ["CoSb3", { type: "otherNonMetals" }],
  ["Sm", { type: "transition" }],
  ["SmCo5", { type: "inert" }],
  ["Nb", { type: "actinoid" }],
  ["NbCr2", { type: "transition" }],
  ["Cr3Si", { type: "otherNonMetals" }],
  ["ErFe2", { type: "halogens" }],
  ["Li2Ga", { type: "halogens" }],
  ["LaGe3", { type: "otherNonMetals" }],
  ["Ir", { type: "otherNonMetals" }],
  ["IrSb3", { type: "lanthanoid" }],
  ["Mg3La", { type: "actinoid" }],
  ["MnSn2", { type: "otherMetals" }],
  ["Mo3Si", { type: "otherNonMetals" }],
  ["MoSi2", { type: "lanthanoid" }],
  ["NbSi2", { type: "otherNonMetals" }],
  ["Ni3Ti", { type: "halogens" }],
  ["Rh", { type: "halogens" }],
  ["RhSb3", { type: "actinoid" }],
  ["TiSb2", { type: "alkalineEarth" }],
  ["TiSi2", { type: "transition" }],
  ["Cr5Si3", { type: "alkalineEarth" }],
  ["Li2Ga7", { type: "otherMetals" }],
  ["Mo3Sb7", { type: "otherNonMetals" }],
  ["Mo5Si3", { type: "alkali" }],
  ["Ti5Sb8", { type: "lanthanoid" }],
  ["Ti5Si3", { type: "lanthanoid" }],
  ["Be12Ti", { type: "transition" }],
  ["AlN", { type: "inert" }],
  ["Hf", { type: "alkali" }],
  ["Hf3AlN", { type: "lanthanoid" }],
  ["Ti2AlN", { type: "inert" }],
  ["Be17Ti2", { type: "alkalineEarth" }],
  ["Ce2Fe17", { type: "otherNonMetals" }],
  ["Co4Sb12", { type: "actinoid" }],
  ["Sm2Co17", { type: "inert" }],
  ["Au", { type: "transition" }],
  ["Ag75Au25", { type: "inert" }],
  ["Co20Cu80", { type: "lanthanoid" }],
  ["Fe50Co50", { type: "otherMetals" }],
  ["Co30Ni70", { type: "actinoid" }],
  ["Ni57Mo43", { type: "otherMetals" }],
  ["Ni80Mo20", { type: "alkali" }],
  ["Nb2O5", { type: "halogens" }],
  ["Pt", { type: "alkali" }],
  ["PtNb2O5", { type: "inert" }],
  ["V4AlC3", { type: "otherMetals" }],
  ["Cu3VS4", { type: "otherMetals" }],
  ["GaV4S8", { type: "inert" }],
  ["GeV4S8", { type: "otherMetals" }],
  ["Mo5Si3MoSi2", { type: "alkalineEarth" }],
  ["AgCrS2", { type: "transition" }],
  ["Cr2AlC", { type: "transition" }],
  ["Nb2AlC", { type: "alkali" }],
  ["Ti2AlC", { type: "transition" }],
  ["Ti3AlC", { type: "otherMetals" }],
  ["Cd", { type: "alkali" }],
  ["CdCNi3", { type: "alkalineEarth" }],
  ["Cr2GeC", { type: "halogens" }],
  ["ZnCMn3", { type: "transition" }],
  ["CePt3P", { type: "otherMetals" }],
  ["CuInS2", { type: "inert" }],
  ["Y", { type: "lanthanoid" }],
  ["CuYSe2", { type: "alkalineEarth" }],
  ["Nb4AlC3", { type: "otherNonMetals" }],
  ["Ta", { type: "transition" }],
  ["Ta4AlC3", { type: "lanthanoid" }],
  ["Ti3AlC2", { type: "actinoid" }],
  ["BaAu2S2", { type: "alkalineEarth" }],
  ["Mo5SiB2", { type: "lanthanoid" }],
  ["Ti3GeC2", { type: "lanthanoid" }],
  ["Ti3SiC2", { type: "inert" }],
  ["CoCuNi", { type: "inert" }],
  ["NbCoSb", { type: "otherMetals" }],
  ["CoNi2S4", { type: "otherMetals" }],
  ["TiCoSb", { type: "lanthanoid" }],
  ["TaCoSn", { type: "halogens" }],
  ["CuCrO4", { type: "lanthanoid" }],
  ["MgNiPt", { type: "otherNonMetals" }],
  ["Zn(Mn2O4)", { type: "alkali" }],
  ["Sr5Nb4O15", { type: "halogens" }],
  ["SrNbO3", { type: "inert" }],
  ["TiNiSn", { type: "otherNonMetals" }],
  ["Zr", { type: "alkali" }],
  ["ZrNiSn", { type: "lanthanoid" }],
  ["Ag2CrO4", { type: "transition" }],
  ["Yb", { type: "alkali" }],
  ["YbAgCu4", { type: "otherNonMetals" }],
  ["AgGaSe2", { type: "halogens" }],
  ["NbC", { type: "otherMetals" }],
  ["TiC", { type: "halogens" }],
  ["TiN", { type: "otherMetals" }],
  ["BaLaSi2", { type: "lanthanoid" }],
  ["SiC", { type: "inert" }],
  ["LnCuSe2", { type: "lanthanoid" }],
  ["CoFe2O4", { type: "halogens" }],
  ["CuCrSe2", { type: "otherMetals" }],
  ["Cu3Mo6S8", { type: "halogens" }],
  ["Pr", { type: "alkalineEarth" }],
  ["TlGaSe2", { type: "alkalineEarth" }],
  ["Pd", { type: "halogens" }],
  ["Pd5HgSe", { type: "actinoid" }],
  ["La(MnO3)", { type: "lanthanoid" }],
  ["Re", { type: "transition" }],
  ["Mo7Re13C", { type: "inert" }],
  ["Mg97Y2Zn", { type: "otherMetals" }],
  ["Ti4AlN3", { type: "inert" }],
  ["Al4C3", { type: "lanthanoid" }],
  ["Ba5LaSi6", { type: "alkalineEarth" }],
  ["CuCr2Te4", { type: "inert" }],
  ["MeGeO4", { type: "otherNonMetals" }],
  ["La2MgNi9", { type: "halogens" }],
  ["Nd", { type: "actinoid" }],
  ["Nd2MgNi9", { type: "halogens" }],
  ["Na4Ti5O12", { type: "inert" }],
  ["Na3Ti4O9", { type: "otherMetals" }],
  ["Al86Ni8Y6", { type: "actinoid" }],
  ["Pb6Bi2Se9", { type: "actinoid" }],
  ["Ca5Ga2Sb6", { type: "otherNonMetals" }],
  ["Li2Eu5Sn7", { type: "transition" }],
  ["Me3GeO8", { type: "alkali" }],
  ["Li2Sm5Sn7", { type: "actinoid" }],
  ["NaRhO2", { type: "halogens" }],
  ["K3(Al(OH)6)", { type: "otherNonMetals" }],
  ["SrSi2", { type: "inert" }],
  ["SrAuSi3", { type: "otherNonMetals" }],
  ["BaTi2Sb2O", { type: "actinoid" }],
  ["MoS2", { type: "inert" }],
  ["Ga8Sb32S60", { type: "actinoid" }],
  ["K2(Zn(OH)4)", { type: "alkali" }],
  ["Al86Ni8La6", { type: "otherNonMetals" }],
  ["Na(Al(OH)4)", { type: "lanthanoid" }],
  ["H(SnCl3)", { type: "alkalineEarth" }],
  ["H2(SiF6)", { type: "otherNonMetals" }],
  ["Pr6O11", { type: "transition" }],
  ["Ln3IrO7", { type: "otherMetals" }],
  ["Ba8Ga15Ge31", { type: "otherNonMetals" }],
  ["H(CuCl2)", { type: "inert" }],
  ["Se65Ga30In5", { type: "lanthanoid" }],
  ["Ba4Mo12S18", { type: "alkalineEarth" }],
  ["K(Pb(OH)3)", { type: "alkali" }],
  ["La2O3MoSi2", { type: "otherMetals" }],
  ["Al50Ti40Si10", { type: "otherMetals" }],
  ["Bi38Mo7", { type: "alkalineEarth" }],
  ["Fe50Co40Ni10", { type: "alkali" }],
  ["Ni60Fe30Cr10", { type: "otherNonMetals" }],
  ["Cu50Zr40Ti10", { type: "actinoid" }],
  ["Cu60Zr30Ti10", { type: "alkalineEarth" }],
  ["Ni60Fe30Mn10", { type: "lanthanoid" }],
  ["Ni60Nb20Zr20", { type: "otherMetals" }],
  ["K2MoS4", { type: "otherNonMetals" }],
  ["K2Mo9S11", { type: "otherNonMetals" }],
  ["CoCrCuNi", { type: "alkali" }],
  ["Na(Sn(OH)3)", { type: "halogens" }],
  ["(Ag(NH3)2)OH", { type: "alkali" }],
  ["Na2(Co(OH)4)", { type: "alkali" }],
  ["Ti3(SiAl)C2", { type: "alkalineEarth" }],
  ["BaCO3", { type: "lanthanoid" }],
  ["BaIrO3", { type: "otherMetals" }],
  ["Ru", { type: "otherNonMetals" }],
  ["BaRuO3", { type: "alkali" }],
  ["Cs2MoS4", { type: "otherNonMetals" }],
  ["CsMo12S14", { type: "transition" }],
  ["Na2(Pb(OH)6)", { type: "actinoid" }],
  ["Na2(Sn(OH)6)", { type: "otherNonMetals" }],
  ["SrCO3", { type: "transition" }],
  ["SrRhO3", { type: "lanthanoid" }],
  ["CoFeRhO4", { type: "lanthanoid" }],
  ["Li2MO3", { type: "lanthanoid" }],
  ["Sr2IrO4", { type: "otherMetals" }],
  ["(Mg50Ti50)94Pd6", { type: "lanthanoid" }],
  ["Sr2RhO4", { type: "alkali" }],
  ["Os", { type: "actinoid" }],
  ["Y2O3", { type: "otherMetals" }],
  ["Ba2YOsO6", { type: "alkali" }],
  ["Ce2O2MnSe2", { type: "otherMetals" }],
  ["AgPb20SbTe20", { type: "actinoid" }],
  ["Ba3N2", { type: "alkali" }],
  ["Si3N4", { type: "lanthanoid" }],
  ["BaYSi4N7", { type: "halogens" }],
  ["La2ZnIrO6", { type: "lanthanoid" }],
  ["CrAl3O6", { type: "halogens" }],
  ["Cs2Mo6Se6", { type: "alkali" }],
  ["MoSe2", { type: "actinoid" }],
  ["Cs2Mo12Se14", { type: "transition" }],
  ["H(TlCl2)", { type: "halogens" }],
  ["Li4Ti5O12", { type: "transition" }],
  ["Rb2Mo6Se6", { type: "otherMetals" }],
  ["Rb2Mo15Se19", { type: "transition" }],
  ["K(Ag(CN)2)", { type: "alkalineEarth" }],
  ["NiCrAlCoW", { type: "otherMetals" }],
  ["SrF2", { type: "halogens" }],
  ["Sr2F2Mn2Se2O", { type: "otherNonMetals" }],
  ["BaSe", { type: "otherMetals" }],
  ["In2Se3", { type: "lanthanoid" }],
  ["Ba2InYbSe5", { type: "halogens" }],
  ["PZT", { type: "lanthanoid" }],
  ["Ti50Cu28Ni15Sn7", { type: "actinoid" }],
  ["Ti45Zr35Ni17Cu3", { type: "transition" }],
  ["NiCrAlCoSi", { type: "inert" }],
  ["Ba3MIr2O9", { type: "lanthanoid" }],
  ["Sr2YRuO6", { type: "inert" }],
  ["ZrO2", { type: "alkalineEarth" }],
  ["Ba5CuIr3O12", { type: "halogens" }],
  ["Ba2LaIrO6", { type: "otherNonMetals" }],
  ["Sc2O3", { type: "otherMetals" }],
  ["Ba2ScIrO6", { type: "actinoid" }],
  ["Sr2ScIrO6", { type: "otherMetals" }],
  ["Lu2O3", { type: "halogens" }],
  ["Sr2LuRuO6", { type: "actinoid" }],
  ["Sr2ScRuO6", { type: "transition" }],
  ["Ca3FeRhO6", { type: "otherMetals" }],
  ["K2(Pb(OH)4)", { type: "lanthanoid" }],
  ["K2(Pb(OH)6)", { type: "transition" }],
  ["Ba14Pd3Ir8O33", { type: "otherMetals" }],
  ["Ba2PrIrO6", { type: "lanthanoid" }],
  ["Ba4BiIr3O12", { type: "transition" }],
  ["Ba16Cu3Ir10O39", { type: "actinoid" }],
]);
export const reactions = [
  ({ reactants: ["O2"], products: ["O3"] },
  { reactants: ["N2O4"], products: ["NO2"] },
  { reactants: ["NO2"], products: ["N2O4"] },
  { reactants: ["C", "O2"], products: ["CO"] },
  { reactants: ["H2", "K"], products: ["KH"] },
  { reactants: ["B", "H2"], products: ["BH3"] },
  { reactants: ["C", "CO2"], products: ["CO"] },
  { reactants: ["C", "O2"], products: ["CO2"] },
  { reactants: ["CO", "S"], products: ["COS"] },
  { reactants: ["F2", "H2"], products: ["HF"] },
  { reactants: ["Fe", "S"], products: ["FeS"] },
  { reactants: ["H2", "I2"], products: ["HI"] },
  { reactants: ["H2", "P"], products: ["PH3"] },
  { reactants: ["H2", "S"], products: ["H2S"] },
  { reactants: ["K", "O2"], products: ["K2O"] },
  { reactants: ["K", "O2"], products: ["KO2"] },
  { reactants: ["N2", "O2"], products: ["NO"] },
  { reactants: ["NO"], products: ["N2", "O2"] },
  { reactants: ["O2", "S"], products: ["SO2"] },
  { reactants: ["Pb", "S"], products: ["PbS"] },
  { reactants: ["S", "Zn"], products: ["ZnS"] },
  { reactants: ["B", "H2"], products: ["B2H6"] },
  { reactants: ["B", "O2"], products: ["B2O3"] },
  { reactants: ["Ba", "O2"], products: ["BaO"] },
  { reactants: ["Be", "O2"], products: ["BeO"] },
  { reactants: ["C", "Fe"], products: ["Fe3C"] },
  { reactants: ["CO", "O2"], products: ["CO2"] },
  { reactants: ["CO2"], products: ["CO", "O2"] },
  { reactants: ["Ca", "O2"], products: ["CaO"] },
  { reactants: ["Cl2", "K"], products: ["KCl"] },
  { reactants: ["Co", "O2"], products: ["CoO"] },
  { reactants: ["Cs", "H2"], products: ["CsH"] },
  { reactants: ["Cu", "O2"], products: ["CuO"] },
  { reactants: ["Fe", "O2"], products: ["FeO"] },
  { reactants: ["Fr", "H2"], products: ["FrH"] },
  { reactants: ["H2", "Li"], products: ["LiH"] },
  { reactants: ["H2", "N2"], products: ["NH3"] },
  { reactants: ["H2", "Na"], products: ["NaH"] },
  { reactants: ["H2", "O2"], products: ["H2O"] },
  { reactants: ["H2", "Rb"], products: ["RbH"] },
  { reactants: ["HClO4"], products: ["H2Cl2O8"] },
  { reactants: ["Hg", "O2"], products: ["HgO"] },
  { reactants: ["K", "O2"], products: ["K2O2"] },
  { reactants: ["Mg", "O2"], products: ["MgO"] },
  { reactants: ["NO", "O2"], products: ["NO2"] },
  { reactants: ["Na", "S"], products: ["Na2S"] },
  { reactants: ["Ni", "O2"], products: ["NiO"] },
  { reactants: ["NiO"], products: ["Ni", "O2"] },
  { reactants: ["O2", "P"], products: ["P2O5"] },
  { reactants: ["O2", "Pb"], products: ["PbO"] },
  { reactants: ["O2", "Ra"], products: ["RaO"] },
  { reactants: ["O2", "Si"], products: ["SiO"] },
  { reactants: ["O2", "Sr"], products: ["SrO"] },
  { reactants: ["O2", "Tl"], products: ["TlO"] },
  { reactants: ["O2", "Zn"], products: ["ZnO"] },
  { reactants: ["Ag2O"], products: ["Ag", "O2"] },
  { reactants: ["Al", "H2"], products: ["AlH3"] },
  { reactants: ["Al", "Ti"], products: ["TiAl"] },
  { reactants: ["As", "Eu"], products: ["EuAs"] },
  { reactants: ["As", "H2"], products: ["AsH3"] },
  { reactants: ["Ba", "H2"], products: ["BaH2"] },
  { reactants: ["Ba", "O2"], products: ["BaO2"] },
  { reactants: ["Be", "H2"], products: ["BeH2"] },
  { reactants: ["Be", "O2"], products: ["BeO2"] },
  { reactants: ["Br2", "H2"], products: ["HBr"] },
  { reactants: ["Ca", "H2"], products: ["CaH2"] },
  { reactants: ["Ca", "O2"], products: ["CaO2"] },
  { reactants: ["Ce", "O2"], products: ["CeO2"] },
  { reactants: ["Cl2", "H2"], products: ["HCl"] },
  { reactants: ["Cl2", "P"], products: ["PCl3"] },
  { reactants: ["Cl2", "P"], products: ["PCl5"] },
  { reactants: ["Cs", "O2"], products: ["Cs2O"] },
  { reactants: ["Cs", "O2"], products: ["CsO2"] },
  { reactants: ["Cu", "O2"], products: ["Cu2O"] },
  { reactants: ["Cu2O"], products: ["Cu", "O2"] },
  { reactants: ["Fr", "O2"], products: ["Fr2O"] },
  { reactants: ["Fr", "O2"], products: ["FrO2"] },
  { reactants: ["Ga", "Li"], products: ["LiGa"] },
  { reactants: ["Ge", "O2"], products: ["GeO2"] },
  { reactants: ["H2", "Mg"], products: ["MgH2"] },
  { reactants: ["H2", "Ra"], products: ["RaH2"] },
  { reactants: ["H2", "Sb"], products: ["SbH3"] },
  { reactants: ["H2", "Se"], products: ["H2Se"] },
  { reactants: ["H2", "Sn"], products: ["SnH4"] },
  { reactants: ["H2", "Sr"], products: ["SrH2"] },
  { reactants: ["H2", "Te"], products: ["H2Te"] },
  { reactants: ["Li", "N2"], products: ["Li3N"] },
  { reactants: ["Li", "O2"], products: ["Li2O"] },
  { reactants: ["Li", "O2"], products: ["LiO2"] },
  { reactants: ["Mg", "O2"], products: ["MgO2"] },
  { reactants: ["Mg", "Ti"], products: ["MgTi"] },
  { reactants: ["Na", "O2"], products: ["Na2O"] },
  { reactants: ["Na", "O2"], products: ["NaO2"] },
  { reactants: ["Ni", "Ti"], products: ["NiTi"] },
  { reactants: ["Ni", "Ti"], products: ["TiNi"] },
  { reactants: ["O2", "Pb"], products: ["PbO2"] },
  { reactants: ["O2", "Ra"], products: ["RaO2"] },
  { reactants: ["O2", "Rb"], products: ["Rb2O"] },
  { reactants: ["O2", "Rb"], products: ["RbO2"] },
  { reactants: ["O2", "SO2"], products: ["SO3"] },
  { reactants: ["O2", "Se"], products: ["SeO2"] },
  { reactants: ["O2", "Si"], products: ["SiO2"] },
  { reactants: ["O2", "Sn"], products: ["SnO2"] },
  { reactants: ["O2", "Sr"], products: ["SrO2"] },
  { reactants: ["O2", "Te"], products: ["TeO2"] },
  { reactants: ["O2", "Th"], products: ["ThO2"] },
  { reactants: ["O2", "Tl"], products: ["Tl2O"] },
  { reactants: ["SO3"], products: ["O2", "SO2"] },
  { reactants: ["Si", "U"], products: ["U3Si2"] },
  { reactants: ["Tl2O"], products: ["O2", "Tl"] },
  { reactants: ["Be", "V"], products: ["Be12V"] },
  { reactants: ["Al", "Ce"], products: ["CeAl3"] },
  { reactants: ["Al", "Cr"], products: ["Cr2Al"] },
  { reactants: ["Al", "O2"], products: ["Al2O3"] },
  { reactants: ["Al", "Ti"], products: ["Al3Ti"] },
  { reactants: ["Al", "Ti"], products: ["Ti3Al"] },
  { reactants: ["As", "O2"], products: ["As2O3"] },
  { reactants: ["Bi", "O2"], products: ["Bi2O3"] },
  { reactants: ["CO", "K"], products: ["K2C2O2"] },
  { reactants: ["Cl2", "Li"], products: ["LiCl"] },
  { reactants: ["Cl2", "NO"], products: ["NOCl"] },
  { reactants: ["Cl2", "Na"], products: ["NaCl"] },
  { reactants: ["Co", "Er"], products: ["ErCo2"] },
  { reactants: ["Co", "O2"], products: ["Co3O4"] },
  { reactants: ["Co", "Sb"], products: ["CoSb3"] },
  { reactants: ["Co", "Sm"], products: ["SmCo5"] },
  { reactants: ["Cr", "Nb"], products: ["NbCr2"] },
  { reactants: ["Cr", "Si"], products: ["Cr3Si"] },
  { reactants: ["Cs", "O2"], products: ["Cs2O2"] },
  { reactants: ["Cu", "CuO"], products: ["Cu2O"] },
  { reactants: ["Cu2O", "O2"], products: ["CuO"] },
  { reactants: ["CuO"], products: ["Cu2O", "O2"] },
  { reactants: ["Er", "Fe"], products: ["ErFe2"] },
  { reactants: ["Fe", "O2"], products: ["Fe2O3"] },
  { reactants: ["Fe", "O2"], products: ["Fe3O4"] },
  { reactants: ["Fr", "O2"], products: ["Fr2O2"] },
  { reactants: ["Ga", "Li"], products: ["Li2Ga"] },
  { reactants: ["Ga", "O2"], products: ["Ga2O3"] },
  { reactants: ["Ge", "GeO2"], products: ["GeO"] },
  { reactants: ["Ge", "La"], products: ["LaGe3"] },
  { reactants: ["H2O2"], products: ["H2O", "O2"] },
  { reactants: ["HClO"], products: ["HCl", "O2"] },
  { reactants: ["In", "O2"], products: ["In2O3"] },
  { reactants: ["Ir", "Sb"], products: ["IrSb3"] },
  { reactants: ["La", "Mg"], products: ["Mg3La"] },
  { reactants: ["La", "O2"], products: ["La2O3"] },
  { reactants: ["Li", "O2"], products: ["Li2O2"] },
  { reactants: ["Mn", "Sn"], products: ["MnSn2"] },
  { reactants: ["Mo", "Si"], products: ["Mo3Si"] },
  { reactants: ["Mo", "Si"], products: ["MoSi2"] },
  { reactants: ["N2O3"], products: ["NO", "NO2"] },
  { reactants: ["N2O5"], products: ["NO2", "O2"] },
  { reactants: ["NO", "NO2"], products: ["N2O3"] },
  { reactants: ["Na", "O2"], products: ["Na2O2"] },
  { reactants: ["Nb", "Si"], products: ["NbSi2"] },
  { reactants: ["Ni", "Ti"], products: ["Ni3Ti"] },
  { reactants: ["O2", "Rb"], products: ["Rb2O2"] },
  { reactants: ["O2", "Sb"], products: ["Sb2O3"] },
  { reactants: ["O2", "SnO"], products: ["SnO2"] },
  { reactants: ["O2", "Tl"], products: ["Tl2O3"] },
  { reactants: ["O2", "U3O8"], products: ["UO3"] },
  { reactants: ["PbO2"], products: ["O2", "PbO"] },
  { reactants: ["Rh", "Sb"], products: ["RhSb3"] },
  { reactants: ["Sb", "Ti"], products: ["TiSb2"] },
  { reactants: ["Si", "SiO2"], products: ["SiO"] },
  { reactants: ["Si", "Ti"], products: ["TiSi2"] },
  { reactants: ["SiO"], products: ["Si", "SiO2"] },
  { reactants: ["Sn", "SnO2"], products: ["SnO"] },
  { reactants: ["SnO"], products: ["Sn", "SnO2"] },
  { reactants: ["UO3"], products: ["O2", "U3O8"] },
  { reactants: ["Al", "Cl2"], products: ["AlCl3"] },
  { reactants: ["BrO2"], products: ["Br2O", "O2"] },
  { reactants: ["CO", "Cl2"], products: ["COCl2"] },
  { reactants: ["CO", "KOH"], products: ["HCOOK"] },
  { reactants: ["Cl2", "Cu"], products: ["CuCl2"] },
  { reactants: ["Cl2", "Fe"], products: ["FeCl3"] },
  { reactants: ["Cl2", "Pb"], products: ["PbCl2"] },
  { reactants: ["Co3O4"], products: ["CoO", "O2"] },
  { reactants: ["CoO", "O2"], products: ["Co3O4"] },
  { reactants: ["Cr", "Si"], products: ["Cr5Si3"] },
  { reactants: ["CrO"], products: ["Cr", "Cr2O3"] },
  { reactants: ["Fe", "Fe2O3"], products: ["FeO"] },
  { reactants: ["Fe", "Fe3O4"], products: ["FeO"] },
  { reactants: ["Fe3O4"], products: ["FeO", "O2"] },
  { reactants: ["FeO", "O2"], products: ["Fe3O4"] },
  { reactants: ["FeO"], products: ["Fe", "Fe3O4"] },
  { reactants: ["Ga", "Li"], products: ["Li2Ga7"] },
  { reactants: ["KClO3"], products: ["KCl", "O2"] },
  { reactants: ["KNO3"], products: ["KNO2", "O2"] },
  { reactants: ["MnO", "O2"], products: ["Mn2O3"] },
  { reactants: ["Mo", "Sb"], products: ["Mo3Sb7"] },
  { reactants: ["Mo", "Si"], products: ["Mo5Si3"] },
  { reactants: ["O2", "PbO"], products: ["Pb3O4"] },
  { reactants: ["Pb3O4"], products: ["O2", "PbO"] },
  { reactants: ["Rb", "RbO2"], products: ["Rb2O"] },
  { reactants: ["Sb", "Ti"], products: ["Ti5Sb8"] },
  { reactants: ["SeO3"], products: ["O2", "SeO2"] },
  { reactants: ["Si", "Ti"], products: ["Ti5Si3"] },
  { reactants: ["SnO"], products: ["Sn", "Sn3O4"] },
  { reactants: ["Be", "Ti"], products: ["Be12Ti"] },
  { reactants: ["AgOH"], products: ["Ag2O", "H2O"] },
  { reactants: ["AlN", "Hf"], products: ["Hf3AlN"] },
  { reactants: ["AlN", "Ti"], products: ["Ti2AlN"] },
  { reactants: ["CO", "Fe"], products: ["Fe(CO)5"] },
  { reactants: ["CO2", "CaO"], products: ["CaCO3"] },
  { reactants: ["CO2", "H2O"], products: ["H2CO3"] },
  { reactants: ["CaCO3"], products: ["CO2", "CaO"] },
  { reactants: ["Ce2O3", "O2"], products: ["CeO2"] },
  { reactants: ["Cl2O", "H2O"], products: ["HClO"] },
  { reactants: ["CrO2"], products: ["Cr2O3", "O2"] },
  { reactants: ["CrO3"], products: ["Cr2O3", "O2"] },
  { reactants: ["CuCO3"], products: ["CO2", "CuO"] },
  { reactants: ["CuOH"], products: ["Cu2O", "H2O"] },
  { reactants: ["FeCO3"], products: ["CO2", "FeO"] },
  { reactants: ["H2CO3"], products: ["CO2", "H2O"] },
  { reactants: ["H2O", "Li2O"], products: ["LiOH"] },
  { reactants: ["H2O", "N2O3"], products: ["HNO2"] },
  { reactants: ["H2O", "N2O5"], products: ["HNO3"] },
  { reactants: ["H2O", "NH3"], products: ["NH4OH"] },
  { reactants: ["H2O", "Na2O"], products: ["NaOH"] },
  { reactants: ["H2O", "Rb2O"], products: ["RbOH"] },
  { reactants: ["H2O", "SO2"], products: ["H2SO3"] },
  { reactants: ["H2O", "SO3"], products: ["H2SO4"] },
  { reactants: ["H2O", "Tl2O"], products: ["TlOH"] },
  { reactants: ["H2SO3"], products: ["H2O", "SO2"] },
  { reactants: ["H2SO4"], products: ["H2O", "SO3"] },
  { reactants: ["HCl", "NH3"], products: ["NH4Cl"] },
  { reactants: ["HNO3"], products: ["H2O", "N2O5"] },
  { reactants: ["Li2O2"], products: ["Li2O", "O2"] },
  { reactants: ["MgCO3"], products: ["CO2", "MgO"] },
  { reactants: ["Mn2O7"], products: ["MnO2", "O2"] },
  { reactants: ["Mn2O7"], products: ["MnO2", "O3"] },
  { reactants: ["MnCO3"], products: ["CO2", "MnO"] },
  { reactants: ["MnO2"], products: ["Mn2O3", "O2"] },
  { reactants: ["NH4Cl"], products: ["HCl", "NH3"] },
  { reactants: ["NiCO3"], products: ["CO2", "NiO"] },
  { reactants: ["O2", "Tl2O"], products: ["Tl2O3"] },
  { reactants: ["PbCO3"], products: ["CO2", "PbO"] },
  { reactants: ["Sn3O4"], products: ["Sn", "SnO2"] },
  { reactants: ["Tl2O3"], products: ["O2", "Tl2O"] },
  { reactants: ["TlOH"], products: ["H2O", "Tl2O"] },
  { reactants: ["ZnCO3"], products: ["CO2", "ZnO"] },
  { reactants: ["Be", "Ti"], products: ["Be17Ti2"] },
  { reactants: ["Ce", "Fe"], products: ["Ce2Fe17"] },
  { reactants: ["Co", "Sb"], products: ["Co4Sb12"] },
  { reactants: ["Co", "Sm"], products: ["Sm2Co17"] },
  { reactants: ["As2O3", "O2"], products: ["As2O5"] },
  { reactants: ["As2O5"], products: ["As2O3", "O2"] },
  { reactants: ["BaO", "NiO"], products: ["BaNiO2"] },
  { reactants: ["Fe3O4", "O2"], products: ["Fe2O3"] },
  { reactants: ["H2N2O2"], products: ["H2O", "N2O"] },
  { reactants: ["H2O", "P2O5"], products: ["H3PO4"] },
  { reactants: ["Mn2O3"], products: ["Mn3O4", "O2"] },
  { reactants: ["Mn2O7", "MnO"], products: ["MnO2"] },
  { reactants: ["NH4NO3"], products: ["H2O", "N2O"] },
  { reactants: ["NaNO3"], products: ["NaNO2", "O2"] },
  { reactants: ["Ni2O3"], products: ["Ni3O4", "O2"] },
  { reactants: ["Ag", "Au"], products: ["Ag75Au25"] },
  { reactants: ["AlO2H"], products: ["Al2O3", "H2O"] },
  { reactants: ["B(OH)3"], products: ["B2O3", "H2O"] },
  { reactants: ["BaO", "H2O"], products: ["Ba(OH)2"] },
  { reactants: ["BeO", "H2O"], products: ["Be(OH)2"] },
  { reactants: ["C", "CrO"], products: ["CO", "Cr"] },
  { reactants: ["C", "CuO"], products: ["CO", "Cu"] },
  { reactants: ["C", "FeO"], products: ["CO", "Fe"] },
  { reactants: ["C", "H2O"], products: ["CO", "H2"] },
  { reactants: ["C", "P2O5"], products: ["CO", "P"] },
  { reactants: ["C", "PbO"], products: ["CO", "Pb"] },
  { reactants: ["C", "ZnO"], products: ["CO", "Zn"] },
  { reactants: ["CO2", "Li2O"], products: ["Li2CO3"] },
  { reactants: ["CO2", "NaOH"], products: ["NaHCO3"] },
  { reactants: ["Ca(OH)2"], products: ["CaO", "H2O"] },
  { reactants: ["CaO", "H2O"], products: ["Ca(OH)2"] },
  { reactants: ["CaO", "MnO2"], products: ["CaMnO3"] },
  { reactants: ["CaO", "SiO2"], products: ["CaSiO3"] },
  { reactants: ["Cl2", "FeCl2"], products: ["FeCl3"] },
  { reactants: ["Cl2O7", "H2O"], products: ["HClO4"] },
  { reactants: ["Co", "Cu"], products: ["Co20Cu80"] },
  { reactants: ["Co", "Fe"], products: ["Fe50Co50"] },
  { reactants: ["Co", "Ni"], products: ["Co30Ni70"] },
  { reactants: ["Co(OH)2"], products: ["CoO", "H2O"] },
  { reactants: ["CrO2"], products: ["Cr2O3", "CrO3"] },
  { reactants: ["CrO3", "H2O"], products: ["H2CrO4"] },
  { reactants: ["Cu(OH)2"], products: ["CuO", "H2O"] },
  { reactants: ["Fe(OH)2"], products: ["FeO", "H2O"] },
  { reactants: ["H2O", "MgO"], products: ["Mg(OH)2"] },
  { reactants: ["H2O", "Mn2O7"], products: ["HMnO4"] },
  { reactants: ["H2O", "P4O10"], products: ["H3PO4"] },
  { reactants: ["H2O", "RaO"], products: ["Ra(OH)2"] },
  { reactants: ["H2O", "SeO2"], products: ["H2SeO3"] },
  { reactants: ["H2O", "SrO"], products: ["Sr(OH)2"] },
  { reactants: ["H2SeO3"], products: ["H2O", "SeO2"] },
  { reactants: ["Mo", "Ni"], products: ["Ni57Mo43"] },
  { reactants: ["Mo", "Ni"], products: ["Ni80Mo20"] },
  { reactants: ["Na2CO3"], products: ["CO2", "Na2O"] },
  { reactants: ["Na2O", "SO3"], products: ["Na2SO4"] },
  { reactants: ["NaOH", "SO3"], products: ["NaHSO4"] },
  { reactants: ["Ni(OH)2"], products: ["H2O", "NiO"] },
  { reactants: ["Pb(OH)2"], products: ["H2O", "PbO"] },
  { reactants: ["SeO2", "SeO3"], products: ["Se2O5"] },
  { reactants: ["Sn(OH)2"], products: ["H2O", "SnO"] },
  { reactants: ["Tl2CO3"], products: ["CO2", "Tl2O"] },
  { reactants: ["Zn(OH)2"], products: ["H2O", "ZnO"] },
  { reactants: ["BaO", "Cu2O"], products: ["BaCu2O2"] },
  { reactants: ["C", "SiO2"], products: ["CO", "Si"] },
  { reactants: ["C", "SnO2"], products: ["CO", "Sn"] },
  { reactants: ["CO", "SO2"], products: ["CO2", "S"] },
  { reactants: ["CO2", "Mg"], products: ["C", "MgO"] },
  { reactants: ["Cl2", "Cu2O"], products: ["Cu2Cl2O"] },
  { reactants: ["CoO", "SiO2"], products: ["Co2SiO4"] },
  { reactants: ["CrO2Cl2"], products: ["Cl2", "CrO2"] },
  { reactants: ["CrO3", "H2O"], products: ["H2Cr2O7"] },
  { reactants: ["H2", "WO3"], products: ["H2O", "W"] },
  { reactants: ["H2O", "K"], products: ["H2", "KOH"] },
  { reactants: ["H2O", "UO3"], products: ["UO2(OH)2"] },
  { reactants: ["H2S", "O2"], products: ["H2O", "S"] },
  { reactants: ["Na2O", "P2O5"], products: ["Na3PO4"] },
  { reactants: ["Nb2O5", "Pt"], products: ["PtNb2O5"] },
  { reactants: ["NiO", "SiO2"], products: ["Ni2SiO4"] },
  { reactants: ["SiO2", "ThO2"], products: ["ThSiO4"] },
  { reactants: ["Th(OH)4"], products: ["H2O", "ThO2"] },
  { reactants: ["UO2(OH)2"], products: ["H2O", "UO3"] },
  { reactants: ["Al", "C", "V"], products: ["V4AlC3"] },
  { reactants: ["Al(OH)3"], products: ["Al2O3", "H2O"] },
  { reactants: ["Al2O3", "C"], products: ["Al", "CO"] },
  { reactants: ["C", "CaO"], products: ["CO", "CaC2"] },
  { reactants: ["C", "Fe2O3"], products: ["CO", "Fe"] },
  { reactants: ["C", "MnO2"], products: ["CO2", "Mn"] },
  { reactants: ["C", "SiO2"], products: ["CO", "SiO"] },
  { reactants: ["CO", "CuO"], products: ["CO2", "Cu"] },
  { reactants: ["CO", "H2O"], products: ["CO2", "H2"] },
  { reactants: ["CO", "PbO"], products: ["CO2", "Pb"] },
  { reactants: ["CO", "SiO"], products: ["C", "SiO2"] },
  { reactants: ["CO2", "H2"], products: ["CO", "H2O"] },
  { reactants: ["Cl2", "H2S"], products: ["HCl", "S"] },
  { reactants: ["Co(OH)3"], products: ["Co2O3", "H2O"] },
  { reactants: ["CoO", "H2"], products: ["Co", "H2O"] },
  { reactants: ["Cr(OH)3"], products: ["Cr2O3", "H2O"] },
  { reactants: ["Cu", "NO"], products: ["Cu2O", "N2"] },
  { reactants: ["Cu", "S", "V"], products: ["Cu3VS4"] },
  { reactants: ["CuO", "H2"], products: ["Cu", "H2O"] },
  { reactants: ["F2", "UO3"], products: ["O2", "UF6"] },
  { reactants: ["Fe(OH)3"], products: ["Fe2O3", "H2O"] },
  { reactants: ["Fe2O3", "H2O"], products: ["Fe(OH)3"] },
  { reactants: ["FeO", "H2"], products: ["Fe", "H2O"] },
  { reactants: ["FeO(OH)"], products: ["Fe2O3", "H2O"] },
  { reactants: ["Ga", "S", "V"], products: ["GaV4S8"] },
  { reactants: ["Ge", "S", "V"], products: ["GeV4S8"] },
  { reactants: ["H2", "NiO"], products: ["H2O", "Ni"] },
  { reactants: ["H2", "PbO"], products: ["H2O", "Pb"] },
  { reactants: ["H2", "SnO"], products: ["H2O", "Sn"] },
  { reactants: ["H2", "ZnO"], products: ["H2O", "Zn"] },
  { reactants: ["La(OH)3"], products: ["H2O", "La2O3"] },
  { reactants: ["Mo", "Si"], products: ["Mo5Si3MoSi2"] },
  { reactants: ["NH3", "O2"], products: ["H2O", "N2"] },
  { reactants: ["NH3", "O2"], products: ["H2O", "NO"] },
  { reactants: ["Na2C2O4"], products: ["CO", "Na2CO3"] },
  { reactants: ["Na2O", "SiO2"], products: ["Na2SiO3"] },
  { reactants: ["O2", "ZnS"], products: ["SO2", "Zn"] },
  { reactants: ["Th(CO3)2"], products: ["CO2", "ThO2"] },
  { reactants: ["Ag", "Cr", "S"], products: ["AgCrS2"] },
  { reactants: ["Ag2O", "CO"], products: ["Ag", "CO2"] },
  { reactants: ["Ag2O", "H2"], products: ["Ag", "H2O"] },
  { reactants: ["Al", "C", "Cr"], products: ["Cr2AlC"] },
  { reactants: ["Al", "C", "Nb"], products: ["Nb2AlC"] },
  { reactants: ["Al", "C", "Ti"], products: ["Ti2AlC"] },
  { reactants: ["Al", "C", "Ti"], products: ["Ti3AlC"] },
  { reactants: ["Bi2O3", "C"], products: ["Bi", "CO2"] },
  { reactants: ["C", "Cd", "Ni"], products: ["CdCNi3"] },
  { reactants: ["C", "Cr", "Ge"], products: ["Cr2GeC"] },
  { reactants: ["C", "Mn", "Zn"], products: ["ZnCMn3"] },
  { reactants: ["CO", "Cu2O"], products: ["CO2", "Cu"] },
  { reactants: ["CO", "NH3"], products: ["H2O", "HCN"] },
  { reactants: ["Ca", "ThO2"], products: ["CaO", "Th"] },
  { reactants: ["Ce", "P", "Pt"], products: ["CePt3P"] },
  { reactants: ["CrHg", "O2"], products: ["CrO", "Hg"] },
  { reactants: ["Cs", "H2O"], products: ["CsOH", "H2"] },
  { reactants: ["Cu", "In", "S"], products: ["CuInS2"] },
  { reactants: ["Cu", "N2O"], products: ["Cu2O", "N2"] },
  { reactants: ["Cu", "Se", "Y"], products: ["CuYSe2"] },
  { reactants: ["Cu2O", "H2"], products: ["Cu", "H2O"] },
  { reactants: ["CuS", "O2"], products: ["CuO", "SO2"] },
  { reactants: ["FeS", "O2"], products: ["FeO", "SO2"] },
  { reactants: ["Fr", "H2O"], products: ["FrOH", "H2"] },
  { reactants: ["H2", "MoO3"], products: ["H2O", "Mo"] },
  { reactants: ["H2", "SnO2"], products: ["H2O", "Sn"] },
  { reactants: ["H2O", "Li"], products: ["H2", "LiOH"] },
  { reactants: ["H2O", "NO", "O2"], products: ["HNO2"] },
  { reactants: ["H2O", "Na"], products: ["H2", "NaOH"] },
  { reactants: ["H2O", "Rb"], products: ["H2", "RbOH"] },
  { reactants: ["H2O", "Si"], products: ["H2", "SiO2"] },
  { reactants: ["H2O2", "H2S"], products: ["H2O", "S"] },
  { reactants: ["H2S", "O2"], products: ["H2O", "SO3"] },
  { reactants: ["HCl", "Na"], products: ["H2", "NaCl"] },
  { reactants: ["Li2O", "Mg"], products: ["Li", "MgO"] },
  { reactants: ["NH3", "O2"], products: ["H2O", "N2O"] },
  { reactants: ["NO2", "SO2"], products: ["NO", "SO3"] },
  { reactants: ["O2", "PbS"], products: ["PbO", "SO2"] },
  { reactants: ["O2", "ZnS"], products: ["SO2", "ZnO"] },
  { reactants: ["PbO", "PbS"], products: ["Pb", "SO2"] },
  { reactants: ["(NH4)2SO4"], products: ["H2SO4", "NH3"] },
  { reactants: ["Ag2O", "HF"], products: ["AgF", "H2O"] },
  { reactants: ["Ag2O", "HI"], products: ["AgI", "H2O"] },
  { reactants: ["Al", "C", "Nb"], products: ["Nb4AlC3"] },
  { reactants: ["Al", "C", "Ta"], products: ["Ta4AlC3"] },
  { reactants: ["Al", "C", "Ti"], products: ["Ti3AlC2"] },
  { reactants: ["Al", "HCl"], products: ["AlCl3", "H2"] },
  { reactants: ["Al", "PbO"], products: ["Al2O3", "Pb"] },
  { reactants: ["Al2O3", "CoO"], products: ["(CoAl2)O4"] },
  { reactants: ["Au", "Ba", "S"], products: ["BaAu2S2"] },
  { reactants: ["B", "Mo", "Si"], products: ["Mo5SiB2"] },
  { reactants: ["B2O3", "La2O3"], products: ["La(BO2)3"] },
  { reactants: ["Bi2O3", "H2"], products: ["Bi", "H2O"] },
  { reactants: ["Br2", "NaI"], products: ["I2", "NaBr"] },
  { reactants: ["C", "Ge", "Ti"], products: ["Ti3GeC2"] },
  { reactants: ["C", "Si", "Ti"], products: ["Ti3SiC2"] },
  { reactants: ["CO", "Fe2O3"], products: ["CO2", "Fe"] },
  { reactants: ["CO", "Fe3O4"], products: ["CO2", "Fe"] },
  { reactants: ["CO", "MnO2"], products: ["CO2", "MnO"] },
  { reactants: ["Cl2", "HBr"], products: ["Br2", "HCl"] },
  { reactants: ["Co", "Cu", "Ni"], products: ["CoCuNi"] },
  { reactants: ["Co", "Nb", "Sb"], products: ["NbCoSb"] },
  { reactants: ["Co", "Ni", "S"], products: ["CoNi2S4"] },
  { reactants: ["Co", "Sb", "Ti"], products: ["TiCoSb"] },
  { reactants: ["Co", "Sn", "Ta"], products: ["TaCoSn"] },
  { reactants: ["Co3O4", "H2"], products: ["Co", "H2O"] },
  { reactants: ["Cr", "Cu", "O2"], products: ["CuCrO4"] },
  { reactants: ["CrHg3", "O2"], products: ["CrO", "Hg"] },
  { reactants: ["Cu2O", "S"], products: ["Cu2S", "SO2"] },
  { reactants: ["Fe", "H2O"], products: ["Fe3O4", "H2"] },
  { reactants: ["Fe", "HCl"], products: ["FeCl2", "H2"] },
  { reactants: ["Fe2(SO4)3"], products: ["Fe2O3", "SO3"] },
  { reactants: ["Fe2O3", "H2"], products: ["Fe", "H2O"] },
  { reactants: ["Fe2O3", "ZnO"], products: ["Zn(FeO2)2"] },
  { reactants: ["Fe3O4", "H2"], products: ["Fe", "H2O"] },
  { reactants: ["FeO", "H2S"], products: ["FeS", "H2O"] },
  { reactants: ["H2", "MnO2"], products: ["H2O", "MnO"] },
  { reactants: ["H2", "SiO2"], products: ["H2O", "SiO"] },
  { reactants: ["H2CO3", "Na2CO3"], products: ["NaHCO3"] },
  { reactants: ["H2O", "NO2", "O2"], products: ["HNO3"] },
  { reactants: ["H2O", "SiO"], products: ["H2", "SiO2"] },
  { reactants: ["H2SO4", "NH3"], products: ["(NH4)2SO4"] },
  { reactants: ["HCl", "KOH"], products: ["H2O", "KCl"] },
  { reactants: ["HCl", "Mg"], products: ["H2", "MgCl2"] },
  { reactants: ["HCl", "Zn"], products: ["H2", "ZnCl2"] },
  { reactants: ["HNO3"], products: ["H2O", "NO2", "O2"] },
  { reactants: ["La2(CO3)3"], products: ["CO2", "La2O3"] },
  { reactants: ["La2(SO4)3"], products: ["La2O3", "SO3"] },
  { reactants: ["Li2O", "Si"], products: ["Li", "SiO2"] },
  { reactants: ["Mg", "Ni", "Pt"], products: ["MgNiPt"] },
  { reactants: ["Mn2O3", "ZnO"], products: ["Zn(Mn2O4)"] },
  { reactants: ["Nb", "Sr5Nb4O15"], products: ["SrNbO3"] },
  { reactants: ["Ni", "Sn", "Ti"], products: ["TiNiSn"] },
  { reactants: ["Ni", "Sn", "Zr"], products: ["ZrNiSn"] },
  { reactants: ["O2", "SnS"], products: ["SO2", "SnO2"] },
  { reactants: ["Rb", "RbOH"], products: ["H2", "Rb2O"] },
  { reactants: ["Ag", "Cr", "O2"], products: ["Ag2CrO4"] },
  { reactants: ["Ag", "Cu", "Yb"], products: ["YbAgCu4"] },
  { reactants: ["Ag", "Ga", "Se"], products: ["AgGaSe2"] },
  { reactants: ["Al", "Cu2O"], products: ["Al2O3", "Cu"] },
  { reactants: ["Al", "MnO2"], products: ["Al2O3", "Mn"] },
  { reactants: ["Al", "Nb", "NbC"], products: ["Nb2AlC"] },
  { reactants: ["Al", "Ti", "TiC"], products: ["Ti2AlC"] },
  { reactants: ["Al", "Ti", "TiN"], products: ["Ti2AlN"] },
  { reactants: ["Ba", "La", "Si"], products: ["BaLaSi2"] },
  { reactants: ["Br2O", "I2"], products: ["Br2", "I2O5"] },
  { reactants: ["C", "SiC", "Ti"], products: ["Ti3SiC2"] },
  { reactants: ["CO", "Fe2O3"], products: ["CO2", "FeO"] },
  { reactants: ["CO", "Fe3O4"], products: ["CO2", "FeO"] },
  { reactants: ["Ce", "Cu", "Se"], products: ["LnCuSe2"] },
  { reactants: ["Cl2", "H2O"], products: ["HCl", "HClO"] },
  { reactants: ["Cl2", "H2O"], products: ["HCl", "HOCl"] },
  { reactants: ["Co", "Fe", "O2"], products: ["CoFe2O4"] },
  { reactants: ["CoSO4"], products: ["CoO", "O2", "SO2"] },
  { reactants: ["Cr", "Cu", "Se"], products: ["CuCrSe2"] },
  { reactants: ["CrO3", "S"], products: ["Cr2O3", "SO2"] },
  { reactants: ["Cu", "Mo", "S"], products: ["Cu3Mo6S8"] },
  { reactants: ["Cu", "Pr", "Se"], products: ["LnCuSe2"] },
  { reactants: ["Cu", "Se", "Sm"], products: ["LnCuSe2"] },
  { reactants: ["Cu2O", "Cu2S"], products: ["Cu", "SO2"] },
  { reactants: ["Cu2S", "O2"], products: ["Cu2O", "SO2"] },
  { reactants: ["FeS", "O2"], products: ["Fe2O3", "SO2"] },
  { reactants: ["Ga", "Se", "Tl"], products: ["TlGaSe2"] },
  { reactants: ["H2", "Mn2O3"], products: ["H2O", "MnO"] },
  { reactants: ["H2", "Rb2O"], products: ["RbH", "RbOH"] },
  { reactants: ["H2O2", "Se"], products: ["H2O", "SeO2"] },
  { reactants: ["HF", "ThO2"], products: ["H2O", "ThF4"] },
  { reactants: ["Hg", "Pd", "Se"], products: ["Pd5HgSe"] },
  { reactants: ["La2O3", "Mn2O3"], products: ["La(MnO3)"] },
  { reactants: ["O2", "SiH4"], products: ["H2O", "SiO2"] },
  { reactants: ["C", "Mo", "Re"], products: ["Mo7Re13C"] },
  { reactants: ["Mg", "Y", "Zn"], products: ["Mg97Y2Zn"] },
  { reactants: ["Rb", "RbNO3"], products: ["N2", "Rb2O"] },
  { reactants: ["Ag2O", "HBr"], products: ["AgBr", "H2O"] },
  { reactants: ["Ag2O", "HCl"], products: ["AgCl", "H2O"] },
  { reactants: ["Al", "Cr2O3"], products: ["Al2O3", "Cr"] },
  { reactants: ["Al", "Fe2O3"], products: ["Al2O3", "Fe"] },
  { reactants: ["Al", "Ti", "TiC"], products: ["Ti3AlC2"] },
  { reactants: ["Al", "Ti", "TiN"], products: ["Ti4AlN3"] },
  { reactants: ["Al4C3", "C", "Ti"], products: ["Ti2AlC"] },
  { reactants: ["As2O3", "HF"], products: ["AsF3", "H2O"] },
  { reactants: ["Ba", "H2O"], products: ["Ba(OH)2", "H2"] },
  { reactants: ["Ba", "La", "Si"], products: ["Ba5LaSi6"] },
  { reactants: ["Bi2O3", "HF"], products: ["BiF3", "H2O"] },
  { reactants: ["C", "Na2SO4"], products: ["CO2", "Na2S"] },
  { reactants: ["CO", "CeO2"], products: ["CO2", "Ce2O3"] },
  { reactants: ["CO2", "Ca(OH)2"], products: ["Ca(HCO3)2"] },
  { reactants: ["CO2", "KOH"], products: ["H2O", "K2CO3"] },
  { reactants: ["Ca", "H2O"], products: ["Ca(OH)2", "H2"] },
  { reactants: ["CaO", "HCl"], products: ["CaCl2", "H2O"] },
  { reactants: ["Cl2", "NaBr"], products: ["Br2", "NaCl"] },
  { reactants: ["CoO", "HCl"], products: ["CoCl2", "H2O"] },
  { reactants: ["Cr", "Cu", "Te"], products: ["CuCr2Te4"] },
  { reactants: ["Cu", "HgCl2"], products: ["CuCl2", "Hg"] },
  { reactants: ["Cu", "ZnSO4"], products: ["CuSO4", "Zn"] },
  { reactants: ["Cu2O", "NH3"], products: ["Cu3N", "H2O"] },
  { reactants: ["CuO", "HCl"], products: ["CuCl2", "H2O"] },
  { reactants: ["CuSO4", "Fe"], products: ["Cu", "FeSO4"] },
  { reactants: ["Fe", "H2O", "O2"], products: ["FeO(OH)"] },
  { reactants: ["Fe", "H2SO4"], products: ["FeSO4", "H2"] },
  { reactants: ["FeC2O4"], products: ["CO", "CO2", "FeO"] },
  { reactants: ["FeCl2", "H2S"], products: ["FeS", "HCl"] },
  { reactants: ["FeO", "HCl"], products: ["FeCl2", "H2O"] },
  { reactants: ["FeS", "HCl"], products: ["FeCl2", "H2S"] },
  { reactants: ["FeSO4", "Zn"], products: ["Fe", "ZnSO4"] },
  { reactants: ["GeO2", "O2", "Zr"], products: ["MeGeO4"] },
  { reactants: ["H2", "MnO2"], products: ["H2O", "Mn2O3"] },
  { reactants: ["H2", "Tl2O3"], products: ["H2O", "Tl2O"] },
  { reactants: ["H2O", "Mg"], products: ["H2", "Mg(OH)2"] },
  { reactants: ["H2O", "NO2"], products: ["HNO2", "HNO3"] },
  { reactants: ["H2O", "Ra"], products: ["H2", "Ra(OH)2"] },
  { reactants: ["H2O", "Sr"], products: ["H2", "Sr(OH)2"] },
  { reactants: ["H2O2", "Tl"], products: ["H2O", "Tl2O3"] },
  { reactants: ["H2S", "NaOH"], products: ["H2O", "Na2S"] },
  { reactants: ["H2S", "PbCl2"], products: ["HCl", "PbS"] },
  { reactants: ["H2S", "ThO2"], products: ["H2O", "ThS2"] },
  { reactants: ["H2SO4", "Zn"], products: ["H2", "ZnSO4"] },
  { reactants: ["HCl", "Li2O"], products: ["H2O", "LiCl"] },
  { reactants: ["HCl", "MgO"], products: ["H2O", "MgCl2"] },
  { reactants: ["HCl", "NaOH"], products: ["H2O", "NaCl"] },
  { reactants: ["HCl", "NiO"], products: ["H2O", "NiCl2"] },
  { reactants: ["HCl", "PbO"], products: ["H2O", "PbCl2"] },
  { reactants: ["HCl", "ZnO"], products: ["H2O", "ZnCl2"] },
  { reactants: ["HCl", "ZnS"], products: ["H2S", "ZnCl2"] },
  { reactants: ["La", "Mg", "Ni"], products: ["La2MgNi9"] },
  { reactants: ["Mg", "Nd", "Ni"], products: ["Nd2MgNi9"] },
  { reactants: ["Na4Ti5O12", "Ti"], products: ["Na3Ti4O9"] },
  { reactants: ["O2", "TiCl4"], products: ["Cl2", "TiO2"] },
  { reactants: ["S", "Tl2O3"], products: ["SO2", "Tl2S3"] },
  { reactants: ["SnC2O4"], products: ["CO", "CO2", "SnO"] },
  { reactants: ["Al", "Ni", "Y"], products: ["Al86Ni8Y6"] },
  { reactants: ["Al", "NaOH"], products: ["H2", "Na3AlO3"] },
  { reactants: ["As2S3", "O2"], products: ["As2O3", "SO2"] },
  { reactants: ["Bi", "Pb", "Se"], products: ["Pb6Bi2Se9"] },
  { reactants: ["Br2", "HgO"], products: ["Br2O", "HgBr2"] },
  { reactants: ["CO", "Fe2O3"], products: ["CO2", "Fe3O4"] },
  { reactants: ["Ca", "Ga", "Sb"], products: ["Ca5Ga2Sb6"] },
  { reactants: ["Cl2", "Fe2O3"], products: ["FeCl3", "O2"] },
  { reactants: ["Cl2", "HgO"], products: ["Cl2O", "HgCl2"] },
  { reactants: ["CuO", "KOH"], products: ["H2O", "K2CuO2"] },
  { reactants: ["Eu", "Li", "Sn"], products: ["Li2Eu5Sn7"] },
  { reactants: ["Fe2O3", "H2"], products: ["Fe3O4", "H2O"] },
  { reactants: ["GeO2", "O2", "Zr"], products: ["Me3GeO8"] },
  { reactants: ["H2O", "N2O4"], products: ["HNO2", "HNO3"] },
  { reactants: ["H2O2", "Tl2O3"], products: ["O2", "TlOH"] },
  { reactants: ["HF", "SiO2"], products: ["H2O", "H2SiF6"] },
  { reactants: ["HI", "SnO2"], products: ["H2O", "H2SnI6"] },
  { reactants: ["La2S3", "O2"], products: ["La2O3", "SO2"] },
  { reactants: ["Li", "Sm", "Sn"], products: ["Li2Sm5Sn7"] },
  { reactants: ["Na2O2", "O2", "Rh"], products: ["NaRhO2"] },
  { reactants: ["NaOH", "Pb"], products: ["H2", "Na2PbO2"] },
  { reactants: ["O2", "PbCO3"], products: ["CO2", "Pb3O4"] },
  { reactants: ["O2", "Sb2S3"], products: ["SO2", "Sb2O3"] },
  { reactants: ["As2S3", "O2"], products: ["As2O5", "SO2"] },
  { reactants: ["AgNO3", "HCl"], products: ["AgCl", "HNO3"] },
  { reactants: ["AgNO3", "KCl"], products: ["AgCl", "KNO3"] },
  { reactants: ["Al", "HNO3"], products: ["Al(NO3)3", "H2"] },
  { reactants: ["Al(OH)3", "KOH"], products: ["K3(Al(OH)6)"] },
  { reactants: ["Al2O3", "HCl"], products: ["AlCl3", "H2O"] },
  { reactants: ["As2O3", "HCl"], products: ["AsCl3", "H2O"] },
  { reactants: ["AsCl3", "H2O"], products: ["As2O3", "HCl"] },
  { reactants: ["Au", "Si", "SrSi2"], products: ["SrAuSi3"] },
  { reactants: ["BaO", "Sb", "Ti"], products: ["BaTi2Sb2O"] },
  { reactants: ["BaS", "ZnSO4"], products: ["BaSO4", "ZnS"] },
  { reactants: ["Bi2O3", "HCl"], products: ["BiCl3", "H2O"] },
  { reactants: ["Br2O", "NaOH"], products: ["H2O", "NaBrO"] },
  { reactants: ["CO2", "H2O", "NH3"], products: ["NH4HCO3"] },
  { reactants: ["CO2", "La2S3"], products: ["CS2", "La2O3"] },
  { reactants: ["CO2", "NaOH"], products: ["H2O", "Na2CO3"] },
  { reactants: ["Co2(CO)8", "O2"], products: ["CO2", "CoO"] },
  { reactants: ["Cr2O3", "HCl"], products: ["CrCl3", "H2O"] },
  { reactants: ["Cr2O3", "KOH"], products: ["H2O", "KCrO2"] },
  { reactants: ["Cr2O3", "NiO", "O2"], products: ["NiCrO4"] },
  { reactants: ["CrO3", "KOH"], products: ["H2O", "K2CrO4"] },
  { reactants: ["Cu", "Mo", "MoS2"], products: ["Cu3Mo6S8"] },
  { reactants: ["Cu(NO3)2"], products: ["CuO", "NO2", "O2"] },
  { reactants: ["Cu2O", "H2O", "O2"], products: ["Cu(OH)2"] },
  { reactants: ["CuO", "H2SO4"], products: ["CuSO4", "H2O"] },
  { reactants: ["Fe2O3", "HCl"], products: ["FeCl3", "H2O"] },
  { reactants: ["FeS", "H2SO4"], products: ["FeSO4", "H2S"] },
  { reactants: ["Ga", "S", "Sb"], products: ["Ga8Sb32S60"] },
  { reactants: ["H2SO4", "KOH"], products: ["H2O", "K2SO4"] },
  { reactants: ["H2SO4", "SnO"], products: ["H2O", "SnSO4"] },
  { reactants: ["H2SO4", "ZnO"], products: ["H2O", "ZnSO4"] },
  { reactants: ["HCl", "La2O3"], products: ["H2O", "LaCl3"] },
  { reactants: ["HNO3", "Tl2O"], products: ["H2O", "TlNO3"] },
  { reactants: ["HNO3", "Zn"], products: ["H2", "Zn(NO3)2"] },
  { reactants: ["KOH", "Zn(OH)2"], products: ["K2(Zn(OH)4)"] },
  { reactants: ["Na2O2", "Ni"], products: ["Na2O", "Ni3O4"] },
  { reactants: ["NaOH", "SO3"], products: ["H2O", "Na2SO4"] },
  { reactants: ["NaOH", "UO3"], products: ["H2O", "Na2UO4"] },
  { reactants: ["Pb(NO3)2"], products: ["NO2", "O2", "PbO"] },
  { reactants: ["Al", "La", "Ni"], products: ["Al86Ni8La6"] },
  { reactants: ["AgNO3", "Al"], products: ["Ag", "Al(NO3)3"] },
  { reactants: ["Al(OH)3", "NaOH"], products: ["Na(Al(OH)4)"] },
  { reactants: ["Bi2O3", "Cl2"], products: ["BiOCl", "Cl2O"] },
  { reactants: ["ClO2", "H2O"], products: ["HClO2", "HClO3"] },
  { reactants: ["ClO3", "H2O"], products: ["HClO3", "HClO4"] },
  { reactants: ["Cr(NO3)3"], products: ["CrO2", "NO2", "O2"] },
  { reactants: ["FeO", "NaOH"], products: ["H2O", "Na4FeO3"] },
  { reactants: ["H2O2", "H2SO3"], products: ["H2O", "H2SO4"] },
  { reactants: ["HCl", "SnO"], products: ["H(SnCl3)", "H2O"] },
  { reactants: ["HCl", "UO3"], products: ["(UO2)Cl2", "H2O"] },
  { reactants: ["HF", "SiO2"], products: ["H2(SiF6)", "H2O"] },
  { reactants: ["Ir", "O2", "Pr6O11"], products: ["Ln3IrO7"] },
  { reactants: ["KMnO4"], products: ["K2MnO4", "MnO2", "O2"] },
  { reactants: ["Na", "Pb(NO3)2"], products: ["NaNO3", "Pb"] },
  { reactants: ["NaOH", "NiO"], products: ["H2O", "Na2NiO2"] },
  { reactants: ["NaOH", "PbO"], products: ["H2O", "Na2PbO2"] },
  { reactants: ["NaOH", "SnO"], products: ["H2O", "Na2SnO2"] },
  { reactants: ["NaOH", "UO3"], products: ["H2O", "Na2U2O7"] },
  { reactants: ["Th(NO3)4"], products: ["NO2", "O2", "ThO2"] },
  { reactants: ["Fe(OH)3"], products: ["Fe3O4", "H2", "H2O"] },
  { reactants: ["AgNO3", "NaCl"], products: ["AgCl", "NaNO3"] },
  { reactants: ["Al", "H2SO4"], products: ["Al2(SO4)3", "H2"] },
  { reactants: ["Al(OH)3", "HCl"], products: ["AlCl3", "H2O"] },
  { reactants: ["Al2O3", "NaOH"], products: ["H2O", "NaAlO2"] },
  { reactants: ["Ba", "Ga", "Ge"], products: ["Ba8Ga15Ge31"] },
  { reactants: ["BaCl2", "H2SO4"], products: ["BaSO4", "HCl"] },
  { reactants: ["BaCl2", "K2SO4"], products: ["BaSO4", "KCl"] },
  { reactants: ["Bi2O3", "Na2O2", "O2"], products: ["NaBiO3"] },
  { reactants: ["Bi2O5", "NaOH"], products: ["H2O", "NaBiO3"] },
  { reactants: ["CO2", "Ca(OH)2"], products: ["CaCO3", "H2O"] },
  { reactants: ["CO2", "H2O", "Na2CO3"], products: ["NaHCO3"] },
  { reactants: ["Ca(OH)2", "HCl"], products: ["CaCl2", "H2O"] },
  { reactants: ["CaCO3", "HCl"], products: ["CaCl2", "H2CO3"] },
  { reactants: ["CaCO3", "Na2S"], products: ["CaS", "Na2CO3"] },
  { reactants: ["CaCO3", "SiO2"], products: ["CO2", "CaSiO3"] },
  { reactants: ["Co(NO3)2"], products: ["Co2O3", "NO2", "O2"] },
  { reactants: ["Cr2O3", "H3PO2"], products: ["CrO", "H3PO4"] },
  { reactants: ["Cu(OH)2", "HCl"], products: ["CuCl2", "H2O"] },
  { reactants: ["Cu2O", "HCl"], products: ["H(CuCl2)", "H2O"] },
  { reactants: ["CuO", "HNO3"], products: ["Cu(NO3)2", "H2O"] },
  { reactants: ["Fe2O3", "NaOH"], products: ["H2O", "NaFeO2"] },
  { reactants: ["Ga", "In", "Se"], products: ["Se65Ga30In5"] },
  { reactants: ["H2CO3", "NaOH"], products: ["H2O", "NaHCO3"] },
  { reactants: ["H2O", "LaCl3"], products: ["HCl", "La(OH)3"] },
  { reactants: ["H2S", "Pb(NO3)2"], products: ["HNO3", "PbS"] },
  { reactants: ["H2SO4", "NaCl"], products: ["HCl", "Na2SO4"] },
  { reactants: ["H2SO4", "NaOH"], products: ["H2O", "Na2SO4"] },
  { reactants: ["H2SO4", "NaOH"], products: ["H2O", "NaHSO4"] },
  { reactants: ["H3PO4", "NaOH"], products: ["H2O", "Na3PO4"] },
  { reactants: ["HCl", "Mg(OH)2"], products: ["H2O", "MgCl2"] },
  { reactants: ["HCl", "Na2CO3"], products: ["H2CO3", "NaCl"] },
  { reactants: ["HCl", "Na2SO3"], products: ["H2SO3", "NaCl"] },
  { reactants: ["HCl", "NaHCO3"], products: ["H2CO3", "NaCl"] },
  { reactants: ["HClO4", "P2O5"], products: ["Cl2O7", "HPO3"] },
  { reactants: ["HNO3", "NH4OH"], products: ["H2O", "NH4NO3"] },
  { reactants: ["HNO3", "PbO"], products: ["H2O", "Pb(NO3)2"] },
  { reactants: ["K2CO3", "SiO2"], products: ["CO2", "K2SiO3"] },
  { reactants: ["K2Cr2O7", "S"], products: ["Cr2O3", "K2SO4"] },
  { reactants: ["K2SeO4", "SO3"], products: ["K2SO4", "SeO3"] },
  { reactants: ["MgCO3", "SiO2"], products: ["CO2", "MgSiO3"] },
  { reactants: ["NaHCO3"], products: ["CO2", "H2O", "Na2CO3"] },
  { reactants: ["NaOH", "SeO2"], products: ["H2O", "Na2SeO3"] },
  { reactants: ["NaOH", "SiO2"], products: ["H2O", "Na2SiO3"] },
  { reactants: ["NaOH", "SiO2"], products: ["H2O", "Na4SiO4"] },
  { reactants: ["NaOH", "SnO2"], products: ["H2O", "Na2SnO3"] },
  { reactants: ["NaOH", "Tl2O3"], products: ["H2O", "NaTlO2"] },
  { reactants: ["Th(C2O4)2"], products: ["CO", "CO2", "ThO2"] },
  { reactants: ["Al4C3", "Ti", "TiAl"], products: ["Ti3AlC2"] },
  { reactants: ["Bi(NO3)3"], products: ["Bi2O3", "NO2", "O2"] },
  { reactants: ["HNO3", "P4O10"], products: ["H3PO4", "N2O5"] },
  { reactants: ["La(NO3)3"], products: ["La2O3", "NO2", "O2"] },
  { reactants: ["(NH4)2U2O7"], products: ["H2O", "NH3", "UO3"] },
  { reactants: ["BaS", "Mo", "MoS2"], products: ["Ba4Mo12S18"] },
  { reactants: ["H2O", "KOH", "PbO"], products: ["K(Pb(OH)3)"] },
  { reactants: ["H2SO4", "UO3"], products: ["(UO2)SO4", "H2O"] },
  { reactants: ["H3PO4", "NaOH"], products: ["H2O", "Na2HPO4"] },
  { reactants: ["H3PO4", "NaOH"], products: ["H2O", "NaH2PO4"] },
  { reactants: ["HCl", "SnO2"], products: ["H2(SnCl6)", "H2O"] },
  { reactants: ["HNO3", "ThO2"], products: ["H2O", "Th(NO3)4"] },
  { reactants: ["La2(SO4)3"], products: ["La2O3", "O2", "SO2"] },
  { reactants: ["La2O3", "Mo", "Si"], products: ["La2O3MoSi2"] },
  { reactants: ["NaHCO3", "NaOH"], products: ["H2O", "Na2CO3"] },
  { reactants: ["NaHSO4", "NaOH"], products: ["H2O", "Na2SO4"] },
  { reactants: ["Al", "Si", "Ti"], products: ["Al50Ti40Si10"] },
  { reactants: ["Bi2O3", "Mo", "MoO3"], products: ["Bi38Mo7"] },
  { reactants: ["Co", "Fe", "Ni"], products: ["Fe50Co40Ni10"] },
  { reactants: ["Cr", "Fe", "Ni"], products: ["Ni60Fe30Cr10"] },
  { reactants: ["Cu", "Ti", "Zr"], products: ["Cu50Zr40Ti10"] },
  { reactants: ["Cu", "Ti", "Zr"], products: ["Cu60Zr30Ti10"] },
  { reactants: ["Fe", "Mn", "Ni"], products: ["Ni60Fe30Mn10"] },
  { reactants: ["Nb", "Ni", "Zr"], products: ["Ni60Nb20Zr20"] },
  { reactants: ["Al(OH)3", "NaOH"], products: ["H2O", "NaAlO2"] },
  { reactants: ["AlCl3", "NaOH"], products: ["Al(OH)3", "NaCl"] },
  { reactants: ["BaCl2", "Na2SO4"], products: ["BaSO4", "NaCl"] },
  { reactants: ["CO2", "CaCO3", "H2O"], products: ["Ca(HCO3)2"] },
  { reactants: ["CO2", "H2O", "La2O3"], products: ["LaCO3(OH)"] },
  { reactants: ["CO2", "H2O", "PbO"], products: ["Pb2(OH)2CO3"] },
  { reactants: ["Ca(HCO3)2"], products: ["CO2", "CaCO3", "H2O"] },
  { reactants: ["Ca(OH)2", "H2CO3"], products: ["CaCO3", "H2O"] },
  { reactants: ["Ca(OH)2", "H2SO4"], products: ["CaSO4", "H2O"] },
  { reactants: ["CaCO3", "Zn"], products: ["CO", "CaO", "ZnO"] },
  { reactants: ["CeO2", "H2SO4"], products: ["Ce(SO4)2", "H2O"] },
  { reactants: ["Cr2O3", "Na2CO3"], products: ["CO2", "NaCrO2"] },
  { reactants: ["CrO2", "H2O"], products: ["CrO(OH)", "H2CrO4"] },
  { reactants: ["Cu", "HCl", "O2"], products: ["CuCl2", "H2O"] },
  { reactants: ["Cu2CO3(OH)2"], products: ["CO2", "CuO", "H2O"] },
  { reactants: ["CuCl2", "NaOH"], products: ["Cu(OH)2", "NaCl"] },
  { reactants: ["CuI", "KOH"], products: ["Cu2O", "H2O", "KI"] },
  { reactants: ["CuSO4", "NaCl"], products: ["CuCl2", "Na2SO4"] },
  { reactants: ["F2", "NaOH"], products: ["H2O", "NaF", "OF2"] },
  { reactants: ["Fe(OH)2", "H2SO4"], products: ["FeSO4", "H2O"] },
  { reactants: ["Fe2O3", "Na2CO3"], products: ["CO2", "NaFeO2"] },
  { reactants: ["FeCl3", "NaOH"], products: ["Fe(OH)3", "NaCl"] },
  { reactants: ["H2SO4", "MnO2"], products: ["H2O", "Mn(SO4)2"] },
  { reactants: ["H2SO4", "NaNO3"], products: ["HNO3", "Na2SO4"] },
  { reactants: ["H2SO4", "NaNO3"], products: ["HNO3", "NaHSO4"] },
  { reactants: ["H2SO4", "SnO2"], products: ["H2O", "Sn(SO4)2"] },
  { reactants: ["HNO3", "Tl2O3"], products: ["H2O", "Tl(NO3)3"] },
  { reactants: ["K2Cr2O7"], products: ["Cr2O3", "K2CrO4", "O2"] },
  { reactants: ["K2MoS4", "Mo", "MoS2"], products: ["K2Mo9S11"] },
  { reactants: ["La2(C2O4)3"], products: ["CO", "CO2", "La2O3"] },
  { reactants: ["Na2CO3", "SiO2"], products: ["CO2", "Na2SiO3"] },
  { reactants: ["Na2Cr2O7", "S"], products: ["Cr2O3", "Na2SO4"] },
  { reactants: ["Na2HPO4", "NaOH"], products: ["H2O", "Na3PO4"] },
  { reactants: ["Na2S", "Pb(NO3)2"], products: ["NaNO3", "PbS"] },
  { reactants: ["NaH2PO4", "NaOH"], products: ["H2O", "Na3PO4"] },
  { reactants: ["Pb(NO3)2", "Zn"], products: ["Pb", "Zn(NO3)2"] },
  { reactants: ["(NH4)2Cr2O7"], products: ["Cr2O3", "H2O", "N2"] },
  { reactants: ["Br2", "H2O", "PbO"], products: ["HBr", "PbO2"] },
  { reactants: ["C", "Cl2", "Cr2O3"], products: ["CO", "CrCl3"] },
  { reactants: ["C", "Cl2", "La2O3"], products: ["CO", "LaCl3"] },
  { reactants: ["Ca(OH)2", "H3PO4"], products: ["CaHPO4", "H2O"] },
  { reactants: ["Co", "Cr", "Cu", "Ni"], products: ["CoCrCuNi"] },
  { reactants: ["CoCl2", "H2O"], products: ["Cl2", "CoO", "H2"] },
  { reactants: ["H2", "O2", "SiCl4"], products: ["HCl", "SiO2"] },
  { reactants: ["H2O", "NaOH", "SnO"], products: ["Na(Sn(OH)3)"] },
  { reactants: ["HNO3", "Sn"], products: ["H2O", "NO2", "SnO2"] },
  { reactants: ["(FCO)2O2", "KI"], products: ["CO2", "I2", "KF"] },
  { reactants: ["Ag", "HNO3"], products: ["AgNO3", "H2O", "NO2"] },
  { reactants: ["Ag2O", "H2O", "NH3"], products: ["(Ag(NH3)2)OH"] },
  { reactants: ["AgNO3", "CaCl2"], products: ["AgCl", "Ca(NO3)2"] },
  { reactants: ["Al2O3", "H2O", "KOH"], products: ["K3(Al(OH)6)"] },
  { reactants: ["CO", "Cl2", "ThO2"], products: ["CO2", "ThCl4"] },
  { reactants: ["Ca(OH)2", "HNO3"], products: ["Ca(NO3)2", "H2O"] },
  { reactants: ["Ca(OH)2", "Na2CO3"], products: ["CaCO3", "NaOH"] },
  { reactants: ["CaCO3", "HNO3"], products: ["Ca(NO3)2", "H2CO3"] },
  { reactants: ["CoO", "H2O", "NaOH"], products: ["Na2(Co(OH)4)"] },
  { reactants: ["Cu2O", "HCl", "O2"], products: ["CuCl2", "H2O"] },
  { reactants: ["CuSO4", "NaOH"], products: ["Cu(OH)2", "Na2SO4"] },
  { reactants: ["FeSO4", "NaOH"], products: ["Fe(OH)2", "Na2SO4"] },
  { reactants: ["H2SO4", "Na2SO3"], products: ["H2SO3", "Na2SO4"] },
  { reactants: ["H2SO4", "Pb(NO3)2"], products: ["HNO3", "PbSO4"] },
  { reactants: ["H2SO4", "Tl2O3"], products: ["H2O", "TlH(SO4)2"] },
  { reactants: ["HNO3", "Zn(OH)2"], products: ["H2O", "Zn(NO3)2"] },
  { reactants: ["HgS", "NaOH"], products: ["H2O", "HgO", "Na2S"] },
  { reactants: ["NH4HCO3", "NaCl"], products: ["NH4Cl", "NaHCO3"] },
  { reactants: ["NaOH", "ZnSO4"], products: ["Na2SO4", "Zn(OH)2"] },
  { reactants: ["(Ag(NH3)2)OH"], products: ["Ag2NH", "H2O", "NH3"] },
  { reactants: ["Al", "C", "Si", "Ti"], products: ["Ti3(SiAl)C2"] },
  { reactants: ["Al2O3", "H2O", "NaOH"], products: ["Na(Al(OH)4)"] },
  { reactants: ["BaCO3", "Ir", "O2"], products: ["BaIrO3", "CO2"] },
  { reactants: ["BaCO3", "O2", "Ru"], products: ["BaRuO3", "CO2"] },
  { reactants: ["CeO2", "HCl"], products: ["CeCl3", "Cl2", "H2O"] },
  { reactants: ["CrO2", "HCl"], products: ["Cl2", "Cr2O3", "H2O"] },
  { reactants: ["Cs2MoS4", "Mo", "MoS2"], products: ["CsMo12S14"] },
  { reactants: ["Cu", "H2SO4"], products: ["CuSO4", "H2O", "SO2"] },
  { reactants: ["H2O", "NaOH", "PbO2"], products: ["Na2(Pb(OH)6)"] },
  { reactants: ["H2O", "NaOH", "SnO2"], products: ["Na2(Sn(OH)6)"] },
  { reactants: ["H2O2", "KMnO4"], products: ["KOH", "MnO2", "O2"] },
  { reactants: ["HCl", "MnO2"], products: ["Cl2", "H2O", "MnCl2"] },
  { reactants: ["HCl", "PbO2"], products: ["Cl2", "H2O", "PbCl2"] },
  { reactants: ["HNO3", "Sn"], products: ["H2O", "H2SnO3", "NO2"] },
  { reactants: ["KOH", "MnO2", "O2"], products: ["H2O", "K2MnO4"] },
  { reactants: ["O2", "Rh", "SrCO3"], products: ["CO2", "SrRhO3"] },
  { reactants: ["Al(OH)3", "H2SO4"], products: ["Al2(SO4)3", "H2O"] },
  { reactants: ["Ca(NO3)2", "Na2CO3"], products: ["CaCO3", "NaNO3"] },
  { reactants: ["Ca3(PO4)2", "H2SO4"], products: ["CaSO4", "H3PO4"] },
  { reactants: ["CaCO3", "HCl"], products: ["CO2", "CaCl2", "H2O"] },
  { reactants: ["Cl2", "NaOH"], products: ["H2O", "NaCl", "NaClO"] },
  { reactants: ["Co", "Fe2O3", "O2", "Rh"], products: ["CoFeRhO4"] },
  { reactants: ["Co2O3", "HCl"], products: ["Cl2", "CoCl2", "H2O"] },
  { reactants: ["Co3O4", "HCl"], products: ["Cl2", "CoCl2", "H2O"] },
  { reactants: ["Cu", "HNO3"], products: ["Cu(NO3)2", "H2O", "NO"] },
  { reactants: ["Cu(NO3)2", "NaOH"], products: ["Cu(OH)2", "NaNO3"] },
  { reactants: ["Cu2O", "H2SO4"], products: ["Cu", "CuSO4", "H2O"] },
  { reactants: ["CuO", "NH4Cl"], products: ["CuCl2", "H2O", "NH3"] },
  { reactants: ["H2SO4", "MnO2"], products: ["H2O", "MnSO4", "O2"] },
  { reactants: ["H2SO4", "PbO2"], products: ["H2O", "O2", "PbSO4"] },
  { reactants: ["HCl", "Na2CO3"], products: ["CO2", "H2O", "NaCl"] },
  { reactants: ["HCl", "Na2SO3"], products: ["H2O", "NaCl", "SO2"] },
  { reactants: ["HCl", "NaHCO3"], products: ["CO2", "H2O", "NaCl"] },
  { reactants: ["Ir", "Li2CO3", "O2"], products: ["CO2", "Li2MO3"] },
  { reactants: ["Ir", "O2", "SrCO3"], products: ["CO2", "Sr2IrO4"] },
  { reactants: ["Li2CO3", "O2", "Pt"], products: ["CO2", "Li2MO3"] },
  { reactants: ["Li2CO3", "O2", "Ru"], products: ["CO2", "Li2MO3"] },
  { reactants: ["Mg", "Pd", "Ti"], products: ["(Mg50Ti50)94Pd6"] },
  { reactants: ["N2O", "NaNH2"], products: ["NH3", "NaN3", "NaOH"] },
  { reactants: ["NaOH", "Pb(NO3)2"], products: ["NaNO3", "Pb(OH)2"] },
  { reactants: ["O2", "Rh", "SrCO3"], products: ["CO2", "Sr2RhO4"] },
  { reactants: ["CuFeS2", "O2"], products: ["CuO", "Fe2O3", "SO2"] },
  { reactants: ["BaO2", "O2", "Os", "Y2O3"], products: ["Ba2YOsO6"] },
  { reactants: ["CeO2", "Mn", "Se"], products: ["Ce2O2MnSe2", "O2"] },
  { reactants: ["Cu", "HNO3"], products: ["Cu(NO3)2", "H2O", "NO2"] },
  { reactants: ["Cu2O", "H2SO4"], products: ["CuSO4", "H2O", "SO2"] },
  { reactants: ["H2", "KMnO4"], products: ["H2O", "K2MnO4", "MnO2"] },
  { reactants: ["HNO3", "Pb"], products: ["H2O", "NO2", "Pb(NO3)2"] },
  { reactants: ["Ag", "Pb", "Sb", "Te"], products: ["AgPb20SbTe20"] },
  { reactants: ["AgNO3", "NaOH"], products: ["Ag2O", "H2O", "NaNO3"] },
  { reactants: ["Al", "H2O", "KOH"], products: ["H2", "K3(Al(OH)6)"] },
  { reactants: ["Ba", "Ba3N2", "Si3N4", "Y"], products: ["BaYSi4N7"] },
  { reactants: ["Ba(NO3)2", "CuSO4"], products: ["BaSO4", "Cu(NO3)2"] },
  { reactants: ["BrO2", "NaOH"], products: ["H2O", "NaBr", "NaBrO3"] },
  { reactants: ["CO2", "H2O", "NaClO"], products: ["HClO", "NaHCO3"] },
  { reactants: ["Ca(OH)2", "Na3PO4"], products: ["Ca3(PO4)2", "NaOH"] },
  { reactants: ["CaCO3", "H2SO4"], products: ["CO2", "CaSO4", "H2O"] },
  { reactants: ["Co3O4", "NaOH", "O2"], products: ["H2O", "NaCoO2"] },
  { reactants: ["Cr2O3", "KNO2", "KNO3"], products: ["K2CrO4", "NO"] },
  { reactants: ["Fe3O4", "HCl"], products: ["FeCl2", "FeCl3", "H2O"] },
  { reactants: ["FeO", "HNO3"], products: ["Fe(NO3)3", "H2O", "NO2"] },
  { reactants: ["HNO3", "PbO2"], products: ["H2O", "O2", "Pb(NO3)2"] },
  { reactants: ["Ir", "La2O3", "O2", "ZnO"], products: ["La2ZnIrO6"] },
  { reactants: ["Na2CO3", "SnCl2"], products: ["CO2", "NaCl", "SnO"] },
  { reactants: ["NaOH", "TlCl3"], products: ["H2O", "NaCl", "Tl2O3"] },
  { reactants: ["Al(OH)3", "Cr", "O2"], products: ["CrAl3O6", "H2O"] },
  { reactants: ["Cs2Mo6Se6", "Mo", "MoSe2"], products: ["Cs2Mo12Se14"] },
  { reactants: ["Cu2O", "HNO3"], products: ["Cu(NO3)2", "H2O", "NO2"] },
  { reactants: ["H2SO4", "Mn2O3"], products: ["H2O", "MnO2", "MnSO4"] },
  { reactants: ["HCl", "Tl2O3"], products: ["Cl2", "H(TlCl2)", "H2O"] },
  { reactants: ["Li2CO3", "O2", "Ti"], products: ["CO2", "Li4Ti5O12"] },
  { reactants: ["NH3OHCl", "NaNO2"], products: ["H2O", "N2O", "NaCl"] },
  { reactants: ["Mo", "MoSe2", "Rb2Mo6Se6"], products: ["Rb2Mo15Se19"] },
  { reactants: ["Ag2O", "H2O", "KCN"], products: ["K(Ag(CN)2)", "KOH"] },
  { reactants: ["Al", "Co", "Cr", "Ni", "W"], products: ["NiCrAlCoW"] },
  { reactants: ["C", "H2S", "La2O3"], products: ["CO", "H2", "La2S3"] },
  { reactants: ["CO", "H2O", "PbCl2"], products: ["CO2", "HCl", "Pb"] },
  { reactants: ["Cu2O", "NaHSO3"], products: ["Cu", "H2SO4", "Na2SO4"] },
  { reactants: ["FeCl3", "H2O", "NH3"], products: ["Fe(OH)3", "NH4Cl"] },
  { reactants: ["H(CuCl2)", "NaOH"], products: ["Cu2O", "H2O", "NaCl"] },
  { reactants: ["H2SO4", "KMnO4"], products: ["H2O", "K2SO4", "Mn2O7"] },
  { reactants: ["H2SO4", "KMnO4"], products: ["H2O", "KHSO4", "Mn2O7"] },
  { reactants: ["H2SO4", "Na2CO3"], products: ["CO2", "H2O", "Na2SO4"] },
  { reactants: ["H2SO4", "Na2SO3"], products: ["H2O", "Na2SO4", "SO2"] },
  { reactants: ["Mn", "Se", "SrF2", "SrO"], products: ["Sr2F2Mn2Se2O"] },
  { reactants: ["Fe3O4", "HNO3"], products: ["Fe(NO3)3", "H2O", "NO2"] },
  { reactants: ["BaSe", "In2Se3", "Se", "Yb"], products: ["Ba2InYbSe5"] },
  { reactants: ["Bi2O3", "Na2O2", "NaOH"], products: ["H2O", "Na3BiO4"] },
  { reactants: ["Ca3(PO4)2", "H2SO4"], products: ["Ca(H2PO4)2", "CaSO4"] },
  { reactants: ["HNO3", "Pb3O4"], products: ["H2O", "Pb(NO3)2", "PbO2"] },
  { reactants: ["O2", "Pb2CO3(OH)2"], products: ["CO2", "H2O", "Pb3O4"] },
  { reactants: ["O2", "PbCO3", "TiO2", "Zr"], products: ["CO2", "PZT"] },
  { reactants: ["Cu", "Ni", "Sn", "Ti"], products: ["Ti50Cu28Ni15Sn7"] },
  { reactants: ["Cu", "Ni", "Ti", "Zr"], products: ["Ti45Zr35Ni17Cu3"] },
  { reactants: ["(NH4)2SO4", "NaOH"], products: ["H2O", "NH3", "Na2SO4"] },
  { reactants: ["Al", "Co", "Cr", "Ni", "Si"], products: ["NiCrAlCoSi"] },
  { reactants: ["KHSO4", "ThO2"], products: ["H2O", "K2SO4", "Th(SO4)2"] },
  { reactants: ["NaOH", "Sn(SO4)2"], products: ["H2O", "Na2SO4", "SnO2"] },
  { reactants: ["H2SO4", "Na2Cr2O7"], products: ["CrO3", "H2O", "Na2SO4"] },
  { reactants: ["H2SO4", "Na2Si3O7"], products: ["H2O", "Na2SO4", "SiO2"] },
  { reactants: ["Fe3O4", "NaOH"], products: ["H2O", "Na4FeO3", "Na5FeO4"] },
  { reactants: ["(NH4)2SO4", "Ca(OH)2"], products: ["CaSO4", "H2O", "NH3"] },
  { reactants: ["Bi2O3", "ClO2", "KOH"], products: ["Bi2O5", "H2O", "KCl"] },
  { reactants: ["BaCO3", "Ir", "MgO", "O2"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "Ir", "O2", "ZnO"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["CaCO3", "Na2CO3", "SiO2"], products: ["CO2", "Na2CaSi6O14"] },
  { reactants: ["KClO3", "KOH", "MnO2"], products: ["H2O", "K2MnO4", "KCl"] },
  { reactants: ["O2", "Ru", "SrCO3", "Y2O3"], products: ["CO2", "Sr2YRuO6"] },
  { reactants: ["BaCO3", "Ir", "O2", "TiO2"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "Ir", "O2", "ZrO2"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "CaCO3", "Ir", "O2"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "CuO", "Ir", "O2"], products: ["Ba5CuIr3O12", "CO2"] },
  { reactants: ["BaCO3", "In2O3", "Ir", "O2"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "Ir", "La2O3", "O2"], products: ["Ba2LaIrO6", "CO2"] },
  { reactants: ["BaCO3", "Ir", "O2", "Sc2O3"], products: ["Ba2ScIrO6", "CO2"] },
  { reactants: ["BaCO3", "Ir", "O2", "Sc2O3"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["BaCO3", "Ir", "O2", "SrCO3"], products: ["Ba3MIr2O9", "CO2"] },
  { reactants: ["Ir", "O2", "Sc2O3", "SrCO3"], products: ["CO2", "Sr2ScIrO6"] },
  { reactants: ["Lu2O3", "O2", "Ru", "SrCO3"], products: ["CO2", "Sr2LuRuO6"] },
  { reactants: ["O2", "Ru", "Sc2O3", "SrCO3"], products: ["CO2", "Sr2ScRuO6"] },
  { reactants: ["As2O3", "HNO3", "Zn"], products: ["AsH3", "H2O", "Zn(NO3)2"] },
  {
    reactants: ["Ag2O", "Cr(OH)3", "NaOH"],
    products: ["Ag", "H2O", "Na2CrO4"],
  },
  { reactants: ["CaCO3", "Fe2O3", "O2", "Rh"], products: ["CO2", "Ca3FeRhO6"] },
  {
    reactants: ["H2O", "KMnO4", "MnSO4"],
    products: ["H2SO4", "K2SO4", "MnO2"],
  },
  {
    reactants: ["H2SO4", "MnSO4", "PbO2"],
    products: ["H2O", "HMnO4", "PbSO4"],
  },
  {
    reactants: ["K2(Pb(OH)4)", "K2(Pb(OH)6)"],
    products: ["H2O", "KOH", "Pb3O4"],
  },
  {
    reactants: ["BaCO3", "Ir", "O2", "Pd"],
    products: ["Ba14Pd3Ir8O33", "CO2"],
  },
  {
    reactants: ["Cr2O3", "KNO3", "Na2CO3"],
    products: ["CO2", "KNO2", "Na2CrO4"],
  },
  {
    reactants: ["BaCO3", "Ir", "O2", "Pr6O11"],
    products: ["Ba2PrIrO6", "CO2"],
  },
  {
    reactants: ["Cr(OH)3", "KOH", "PbO2"],
    products: ["H2O", "K2CrO4", "K2PbO2"],
  },
  {
    reactants: ["BaCO3", "Bi2O3", "Ir", "O2"],
    products: ["Ba4BiIr3O12", "CO2"],
  },
  {
    reactants: ["BaCO3", "CuO", "Ir", "O2"],
    products: ["Ba16Cu3Ir10O39", "CO2"],
  }),
];
